Repository fluid-cloudnative/fluid, pull requests merged in 2020-10, with the labels that each got.

#205 Update hostpath demo doc
  docs/zh/samples/hostpath.md
Labels: documentation

#204 Update Change log
  CHANGELOG.md
Labels: documentation

#207 Update docs
  docs/zh/samples/nonroot_access.md
Labels: documentation

#209 Update info of new release
  README-zh_CN.md
  README.md
  docs/zh/TOC.md
Labels: documentation

#212 Add quick demo for accelerate PVC with Fluid
  README-zh_CN.md
  README.md
Labels: documentation

#238 Fix the failure of starting fluid-csi
  Dockerfile.csi
  Makefile
  cmd/csi/main.go
  csi/shell/entrypoint.sh
  version.go
Labels: bug, v0.4.0

#240 Update docker image for csi version
  Makefile
  charts/fluid/fluid/values.yaml
  version.go
Labels: features, v0.4.0

#242 [FEATURES] Support deploy multiple Dataset in the same node
  charts/alluxio/templates/config/alluxio-conf.yaml
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/service.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  cmd/csi/main.go
  pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/alluxio/node.go
  pkg/ddc/alluxio/operations/base_test.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_init_users.go
  pkg/ddc/alluxio/transform_optimization.go
  pkg/ddc/alluxio/transform_optimization_test.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/alluxio/utils.go
  pkg/ddc/alluxio/utils_test.go
  pkg/utils/kubeclient/pod.go
Labels: features, v0.4.0

#256 Support HCFS
  CHANGELOG.md
  api/v1alpha1/common.go
  api/v1alpha1/dataset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  charts/fluid/fluid/values.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  docs/zh/samples/accelerate_data_accessing_by_hdfs.md
  pkg/controllers/runtime_controller.go
  pkg/ddc/alluxio/dataset.go
  pkg/ddc/alluxio/hcfs.go
  pkg/ddc/alluxio/operations/conf.go
  pkg/utils/kubeclient/service.go
Labels: features, v0.4.0

#273 Refactor runtime Implementation
  .circleci/config.yml
  .travis.yml
  Dockerfile.alluxioruntime
  Dockerfile.csi
  Dockerfile.dataset
  Makefile
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/role/ClusterRoleBindind.yaml
  charts/fluid/fluid/templates/role/ServiceAccount
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/values.yaml
  cmd/alluxio/main.go
  cmd/dataset/main.go
  version.go
Labels: features, v0.4.0

#270 Implement DataLoad CRD and DataLoad controller
  PROJECT
  api/v1alpha1/alluxiodataload_types.go
  api/v1alpha1/dataload_types.go
  api/v1alpha1/dataset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-dataloader/templates/configmap.yaml
  charts/fluid-dataloader/templates/dataloader.yaml
  charts/fluid-dataloader/values.yaml
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  cmd/alluxio/main.go
  cmd/dataset/main.go
  config/crd/bases/data.fluid.io_alluxiodataloads.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_dataloads.yaml
  config/crd/patches/webhook_in_dataloads.yaml
  config/rbac/dataload_editor_role.yaml
  config/rbac/dataload_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/data_v1alpha1_dataload.yaml
  pkg/common/constants.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/dataload/implement_test.go
  pkg/dataload/constants.go
  pkg/dataload/context.go
  pkg/dataload/value.go
  pkg/utils/dataload.go
  pkg/utils/dataload_test.go
  pkg/utils/helm/utils.go
  samples/dataload/alluxio_dataloader.yaml
  samples/dataload/dataload.yaml
Labels: features, v0.4.0

#289 Add patch for DataLoad controller
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/utils/dataset_runtime.go
  pkg/utils/random.go
Labels: features, v0.4.0
