Repository fluid-cloudnative/fluid, pull requests merged in 2020-09, with the labels that each got.

#110 Fix some typos and warnings found by static check
  api/v1alpha1/alluxioruntime_types.go
  pkg/common/constants.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
  pkg/csi/fuse/driver.go
  pkg/ddc/alluxio/create_volume.go
  pkg/ddc/alluxio/dataset.go
  pkg/ddc/alluxio/node.go
  pkg/utils/charts.go
  pkg/utils/kubeclient/volume.go
Labels: bug

#111 Let Makefile use tab indent
  Makefile
Labels: bug

#108 Update concept and architecture
  README-zh_CN.md
  README.md
  docs/en/userguide/overview.md
  docs/zh/userguide/overview.md
Labels: documentation

#109 [Doc]Make install.md install Fluid from releases
  docs/en/userguide/install.md
  docs/zh/userguide/install.md
Labels: documentation

#119 Fix sample docs
  docs/en/samples/accelerate_data_accessing.md
  docs/en/samples/data_co_locality.md
  docs/en/userguide/install.md
  docs/zh/samples/accelerate_data_accessing.md
  docs/zh/samples/data_co_locality.md
  docs/zh/userguide/install.md
Labels: documentation

#127 Clean up the code
  cmd/csi/main.go
  pkg/csi/fuse/controller.go
  pkg/csi/fuse/nodeserver.go
  pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/create_volume.go
  pkg/ddc/alluxio/label.go
  pkg/ddc/alluxio/node.go
  pkg/ddc/alluxio/replicas.go
  pkg/ddc/alluxio/shutdown.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/utils.go
  pkg/utils/dataset_condition.go
  pkg/utils/kubeclient/exec.go
  pkg/utils/runtime_condition.go
Labels: bug

#129 [DOC]Rewrite get_started.md
  docs/en/userguide/get_started.md
  docs/zh/userguide/get_started.md
Labels: documentation

#128 Candidate Build for v0.2.0
  Makefile
  README-zh_CN.md
  README.md
  charts/fluid/fluid/values.yaml
  charts/fluid/v0.1.0/CHANGELOG.md
  charts/fluid/v0.1.0/Chart.yaml
  charts/fluid/v0.1.0/README.md
  charts/fluid/v0.1.0/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/v0.1.0/crds/data.fluid.io_datasets.yaml
  charts/fluid/v0.1.0/values.yaml
  charts/fluid/v0.2.0/CHANGELOG.md
  charts/fluid/v0.2.0/README.md
  charts/fluid/v0.2.0/values.yaml
Labels: enhancement

#143 Fix non root issue
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/operations/local_test.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_ufs_test.go
  pkg/ddc/alluxio/trasform_optimization.go
  pkg/ddc/alluxio/trasform_optimization_test.go
  pkg/ddc/alluxio/utils.go
Labels: enhancement

#150 Translate the user id
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/templates/fuse/daemonset.yaml
  pkg/ddc/alluxio/transform.go
Labels: features

#151 Support Non root for hostpah
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_permission.go
Labels: features

#152 Add AdditionalPrinterColumns for AlluxioRuntime CRD
  api/v1alpha1/alluxioruntime_types.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
Labels: features

#154 Update docs
  docs/zh/samples/hostpath.md
Labels: documentation

#159 Make controller-manager's logs more readable
  cmd/controller/main.go
Labels: features

#166 Build new images
  Makefile
  charts/fluid/fluid/values.yaml
Labels: features

#168 Leverage init container to support non-root scenario
  Dockerfile.centos
  Makefile
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  entrypoint.sh
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/utils.go
  pkg/ddc/alluxio/utils_test.go
Labels: features

#169 Update chart and change log for non-root scenario
  Dockerfile.centos
  Makefile
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/docker/init-users/Dockerfile
  charts/alluxio/docker/init-users/entrypoint.sh
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/values.yaml
Labels: features

#170 Refactor helm chart for non root
  Makefile
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/common.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/alluxio/CHANGELOG.md
  charts/alluxio/docker/init-users/entrypoint.sh
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  charts/fluid/fluid/values.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  docs/zh/samples/hostpath.md
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_init_users.go
  pkg/ddc/alluxio/transform_init_users_test.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/utils.go
  pkg/ddc/alluxio/utils_test.go
  samples/ufspath/dataset.yaml
Labels: features

#172 optimize for default setting in alluxio
  charts/alluxio/CHANGELOG.md
  charts/alluxio/values.yaml
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_optimization.go
  pkg/ddc/alluxio/transform_optimization_test.go
  pkg/ddc/alluxio/transform_resources.go
  pkg/ddc/alluxio/transform_resources_test.go
  pkg/ddc/alluxio/transform_test.go
  pkg/ddc/alluxio/trasform_optimization_test.go
  samples/ufspath/dataset.yaml
Labels: features

#173 Add hostpath demo doc(zh version)
  docs/zh/samples/hostpath.md
Labels: documentation

#175 Fix nonroot user tierstore no permission bug
  charts/alluxio/docker/init-users/Dockerfile
  charts/alluxio/docker/init-users/chmod_tierpath.sh
  charts/alluxio/docker/init-users/entrypoint.sh
  charts/alluxio/docker/init-users/init_users.sh
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  pkg/ddc/alluxio/transform_init_users.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/utils.go
Labels: bug

#179 Update helm chart version and docker image
  Makefile
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/docker/init-users/chmod_tierpath.sh
  charts/alluxio/values.yaml
  charts/fluid/fluid/values.yaml
  docs/en/userguide/troubleshooting.md
  docs/zh/userguide/troubleshooting.md
Labels: features

#186 Update pvc docs
  docs/zh/TOC.md
  docs/zh/samples/accelerate_pvc.md
Labels: documentation

#187 Support configurable init image for Alluxio runtime
  charts/fluid/fluid/templates/manager/manager.yaml
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/common/constants.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/transform_init_users.go
  pkg/ddc/alluxio/transform_init_users_test.go
  samples/ufspath/dataset.yaml
Labels: features

#177 Add faq(zh)
  docs/en/samples/machinelearning.md
  docs/en/userguide/troubleshooting.md
  docs/zh/samples/machinelearning.md
  docs/zh/userguide/faq.md
Labels: documentation

#192 Fix Non-root users could not access the dataset
  charts/fluid/fluid/VERSION
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_fuse.go
  pkg/ddc/alluxio/transform_fuse_test.go
  pkg/ddc/alluxio/transform_test.go
Labels: bug

#194 Support dynamic non-root user for fuse
  charts/alluxio/docker/init-users/chmod_fuse_mountpoint.sh
  charts/alluxio/docker/init-users/chmod_tierpath.sh
  charts/alluxio/docker/init-users/entrypoint.sh
  charts/alluxio/docker/init-users/init_users.sh
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/fluid/fluid/VERSION
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_fuse.go
  samples/ufspath/app.yaml
  samples/ufspath/dataset.yaml
Labels: features

#195 update docker images for non-root support
  charts/fluid/fluid/values.yaml
Labels: features

#197 Optimize Fluid
  Makefile
  charts/alluxio/CHANGELOG.md
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/daemonset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/values.yaml
  docs/zh/samples/hostpath.md
  pkg/common/constants.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/transform_fuse_test.go
  pkg/ddc/alluxio/transform_init_users.go
  pkg/ddc/alluxio/transform_optimization.go
  pkg/ddc/alluxio/transform_test.go
  samples/ufspath/app.yaml
  samples/ufsvolume/dataset.yaml
Labels: features
