Repository fluid-cloudnative/fluid, pull requests merged in 2022-12, with the labels that each got.

#2392 Update approvers for prow integration
  OWNERS
Labels: lgtm

#2390 Docker build for fixing alluxio runtime's health check
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2399 Handle no match kind error when on-demand scaling runtime controllers
  pkg/controllers/deploy/runtime_controllers.go
  pkg/ddc/alluxio/health_check.go
  pkg/ddc/alluxio/metadata_test.go
  pkg/ddc/alluxio/replicas_test.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/eac/engine.go
  pkg/utils/crtl_utils.go
  pkg/utils/crtl_utils_test.go
  pkg/utils/runtime_checkers.go
Labels: lgtm, approved

#2403 Fix owner reference for thin runtime
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
  pkg/ddc/thin/referencedataset/engine.go
  pkg/utils/dataset_runtime.go
  pkg/utils/dataset_runtime_test.go
Labels: lgtm, approved

#2395 Add prow test case: alluxio access web ufs
  test/prow/access_web_ufs.py
Labels: lgtm, approved

#2407 Implement node publish secret mount policy
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/thinruntimeprofile_types.go
  charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
  config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
  pkg/ddc/thin/transform_fuse.go
  pkg/ddc/thin/transform_pvc_mounts.go
  pkg/ddc/thin/transform_pvc_mounts_test.go
  pkg/utils/kubeclient/secret.go
Labels: lgtm, approved

#2408 Fix CVE by upgrading alpine base image version
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
Labels: lgtm, approved

#2416 Revert dataset dockerfile base image
  docker/Dockerfile.dataset
Labels: lgtm, approved

#2406 fix bug: set dataset mount.path of local/pvc , do no take effect. the…
  pkg/ddc/alluxio/transform_ufs_test.go
  pkg/ddc/goosefs/transform_ufs_test.go
  pkg/utils/ufs_path_builder.go
Labels: lgtm, needs-ok-to-test, approved

#2384 Issue 2379
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/jindofsx/master_internal.go
Labels: lgtm, approved

#2415 Fix fluid install error
  config/crd/kustomization.yaml
  config/fluid/bases/role/dataset/rbac.yaml
Labels: needs-ok-to-test, approved

#2427 Report dataset not ready message when failed to mutate pod specs
  api/v1alpha1/constant.go
  api/v1alpha1/dataset_types.go
  pkg/controllers/runtime_controller.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
  pkg/webhook/scheduler/mutating/utils.go
Labels: lgtm, approved

#2419 Fix EAC minimum worker quota
  charts/eac/values.yaml
  pkg/ddc/eac/transform_option.go
  pkg/ddc/eac/transform_option_test.go
  pkg/ddc/eac/transform_tieredstore_test.go
Labels: lgtm, needs-ok-to-test, approved

#2431 add e2e test: alluxioruntime resource setting
  test/prow/alluxioruntime_resources_setting.py
Labels: lgtm, needs-ok-to-test, approved

#2438 Add doc for how to use ThinRuntime
  docs/zh/samples/thinruntime.md
Labels: lgtm, approved

#2442 Add eacruntimes in csi rbac
  charts/fluid/fluid/templates/role/csi/rbac.yaml
Labels: lgtm, needs-ok-to-test, approved

#2436 Add prow test case: access oss via jindoruntime
  test/prow/access_oss_via_jindorumtime.py
Labels: lgtm, needs-ok-to-test, approved

#2433 test: e2e testcase 5
  test/prow/patch_node_label_parallel.py
Labels: lgtm, needs-ok-to-test, approved

#2429 testcase: add testcase 12
  test/prow/csi_stable_patch.py
Labels: lgtm, needs-ok-to-test, approved

#2446 Fix EAC probe
  charts/eac/templates/fuse/daemonset.yaml
  charts/eac/templates/master/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#2411 DOC: add english doc 'runtime monitoring'
  docs/en/TOC.md
  docs/en/operation/monitoring.md
Labels: lgtm, needs-ok-to-test, approved

#2455 Rename managed-by label on pvcs
  pkg/common/label.go
  pkg/ddc/thin/wrap_pvc.go
  pkg/ddc/thin/wrap_pvc_test.go
  pkg/utils/kubeclient/volume.go
  pkg/webhook/scheduler/mutating/utils.go
Labels: approved

#2456 Extract volume mount options for ThinRuntime fuse container
  charts/thin/templates/config/runtime.yaml
  pkg/ddc/thin/transform_config.go
  pkg/ddc/thin/type.go
Labels: lgtm, approved

#2459 fix: issue-2367
  pkg/common/thin.go
  pkg/utils/kubeclient/volume_mount.go
  pkg/utils/kubeclient/volume_mount_test.go
Labels: lgtm, approved, ok-to-test

#2468 add cloudview to ADOPTERS.md
  ADOPTERS.md
Labels: needs-ok-to-test, approved

#2441 add e2e test 9-Alluxio动态变更挂载点
  test/prow/alluxio_dynamic_mountpoint.py
Labels: lgtm, needs-ok-to-test, approved

#2432 DOC: Add EAC doc
  charts/eac/CHANGELOG.md
  charts/eac/README.md
  docs/zh/samples/eac_runtime.md
Labels: lgtm, needs-ok-to-test, approved

#2472 Fix fuse sidecar mutation for EACRuntime
  charts/fluid/fluid/templates/role/webhook/rabc.yaml
  pkg/ddc/base/runtime_helper.go
  pkg/utils/kubeclient/volume.go
  pkg/utils/volumes.go
  pkg/utils/volumes_test.go
Labels: lgtm, approved

#2475 DOCFIX: mkdir before mount goofys in ThinRuntime demo
  docs/zh/samples/thinruntime.md
Labels: approved

#2473 test: use `T.Setenv` to set env vars in tests
  pkg/csi/recover/recover_test.go
  pkg/ddc/alluxio/utils_test.go
  pkg/ddc/base/runtime_test.go
  pkg/ddc/eac/utils_test.go
  pkg/ddc/goosefs/utils_test.go
  pkg/ddc/jindo/utils_test.go
  pkg/ddc/jindofsx/utils_test.go
  pkg/ddc/juicefs/utils_test.go
  pkg/ddc/thin/util_test.go
  pkg/utils/charts_test.go
  pkg/utils/common_test.go
  pkg/utils/docker/image_test.go
  pkg/utils/env_test.go
  pkg/utils/kubeclient/exec_test.go
  pkg/utils/mount_test.go
  pkg/utils/mountinfo/mountpoint_test.go
  pkg/utils/runtimes/options/critical_fuse_pod_test.go
  pkg/utils/runtimes/options/init_port_check_test.go
  pkg/webhook/certificate_builder_test.go
Labels: lgtm, needs-ok-to-test, approved

#2465 Check dataLoad's targetPath existence by dataload job's log.
  charts/fluid-dataloader/alluxio/templates/configmap.yaml
  charts/fluid-dataloader/alluxio/templates/dataloader.yaml
  charts/fluid-dataloader/goosefs/templates/configmap.yaml
  charts/fluid-dataloader/goosefs/templates/dataloader.yaml
  charts/fluid-dataloader/jindo/templates/configmap.yaml
  charts/fluid-dataloader/jindo/templates/dataloader.yaml
  charts/fluid-dataloader/jindofsx/templates/configmap.yaml
  charts/fluid-dataloader/juicefs/templates/configmap.yaml
  charts/fluid-dataloader/juicefs/templates/dataloader.yaml
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/utils/kubeclient/pod.go
Labels: lgtm, needs-ok-to-test, approved

#2461 doc: add addon folder to store the thinruntime use case
  addon/en-readme.md
  addon/nfs/en-nfs.md
  addon/nfs/zh-nfs.md
  addon/zh-readme.md
Labels: lgtm, needs-ok-to-test, approved

#2409 DOC: add english doc 'Pod scheduling optimization'
  docs/en/TOC.md
  docs/en/operation/pod_schedule_optimization.md
  docs/zh/TOC.md
  docs/zh/operation/pod_schedule_optimization.md
Labels: lgtm, needs-ok-to-test, approved
