Repository fluid-cloudnative/fluid, pull requests merged in 2023-02, with the labels that each got.

#2548 [BUGFIX]Fix thinruntime resource overridden
  go.mod
  go.sum
  pkg/ddc/thin/transform_fuse_test.go
  pkg/ddc/thin/transform_resources.go
  pkg/ddc/thin/transform_test.go
  pkg/utils/testutil/deepequal.go
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/dsl/behavior.go
  vendor/github.com/agiledragon/gomonkey/v2/dsl/constraint.go
  vendor/github.com/agiledragon/gomonkey/v2/dsl/factory.go
  vendor/github.com/agiledragon/gomonkey/v2/dsl/matcher.go
  vendor/github.com/agiledragon/gomonkey/v2/dsl/patch_builder.go
  vendor/github.com/agiledragon/gomonkey/v2/go.mod
  vendor/github.com/agiledragon/gomonkey/v2/go.sum
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_return_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_seq_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_var_return_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_var_seq_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_func_var_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_global_var_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_interface_reused_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_method_func_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_method_return_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_method_seq_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_method_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/apply_private_method_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/dsl_test/func_dsl_test.go
  vendor/github.com/agiledragon/gomonkey/v2/test/fake/fake.go
  vendor/github.com/agiledragon/gomonkey/v2/test/patch_pair_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: lgtm, approved

#2550 Support event driven reconcilation for cache runtimes
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/templates/config/alluxio-conf.yaml
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/service.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
  charts/alluxio/values.yaml
  charts/eac/CHANGELOG.md
  charts/eac/Chart.yaml
  charts/eac/templates/fuse/daemonset.yaml
  charts/eac/templates/master/statefulset.yaml
  charts/eac/templates/worker/configmap.yaml
  charts/eac/templates/worker/statefulset.yaml
  charts/eac/values.yaml
  charts/jindofsx/templates/config/jindofs-client-conf.yaml
  charts/jindofsx/templates/config/jindofs-conf.yaml
  pkg/ctrl/watch/daemonset.go
  pkg/ctrl/watch/runtime.go
  pkg/ctrl/watch/statefulset.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/eac/transform.go
  pkg/ddc/eac/types.go
Labels: lgtm, approved

#2551 add sidecar.istio.io/inject annotations for alluxio runtime
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
Labels: lgtm, approved

#2555 fix: issue-2553 update dingtack code
  README.md
  static/dingtalk.png
Labels: lgtm, needs-ok-to-test, approved

#2552 add sidecar.istio.io/inject annotations for goosefs runtime
  charts/goosefs/CHANGELOG.md
  charts/goosefs/Chart.yaml
  charts/goosefs/templates/fuse/daemonset.yaml
  charts/goosefs/templates/master/statefulset.yaml
  charts/goosefs/templates/worker/statefulset.yaml
Labels: lgtm, approved

#2559 Setting pv.spec.capacity capacity value to a large initial value.
  pkg/utils/dataset/volume/create.go
Labels: lgtm, needs-ok-to-test, approved

#2560 Support configurable PodMetadata and scale out EACRuntime in parallel
  api/v1alpha1/eacruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/eac/CHANGELOG.md
  charts/eac/Chart.yaml
  charts/eac/templates/fuse/daemonset.yaml
  charts/eac/templates/master/statefulset.yaml
  charts/eac/templates/worker/statefulset.yaml
  charts/eac/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_eacruntimes.yaml
  config/crd/bases/data.fluid.io_eacruntimes.yaml
  pkg/ddc/eac/transform.go
  pkg/ddc/eac/types.go
Labels: lgtm, approved

#2561 Optimize permit sync logic
  pkg/ddc/base/syncs.go
Labels: lgtm, approved

#2563 [juicefs] fix worker cache when set option
  charts/juicefs/CHANGELOG.md
  charts/juicefs/Chart.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_volume.go
  pkg/ddc/juicefs/transform_volume_test.go
Labels: lgtm, approved

#2568 Return early when syncing EAC to speed up scaling
  pkg/ddc/eac/dataset.go
  pkg/ddc/eac/status.go
Labels: lgtm, approved

#2565 Update how-to-develop doc
  docs/zh/dev/how_to_develop.md
Labels: approved

#2572 Increase default reconcile worker num of dataset controller to 3
  cmd/dataset/app/dataset.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
Labels: lgtm, approved

#2576 Fix reference dataset & Fix NPE bug for eacruntime
  charts/fluid/fluid/templates/role/thin/rbac.yaml
  cmd/dataset/app/dataset.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
  pkg/ddc/base/runtime.go
  pkg/ddc/base/runtime_test.go
  pkg/ddc/eac/shutdown.go
  pkg/ddc/thin/referencedataset/cm.go
  pkg/ddc/thin/referencedataset/engine.go
Labels: lgtm, approved

#2569 Fix bug 2521
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_fuse.go
  pkg/ddc/alluxio/transform_test.go
Labels: lgtm, approved

#2542 Fearure for #2531 - for jindofs runtime
  charts/jindofs/CHANGELOG.md
  charts/jindofs/Chart.yaml
  charts/jindofs/templates/fuse/daemonset.yaml
  charts/jindofs/templates/master/statefulset.yaml
  charts/jindofs/templates/worker/statefulset.yaml
Labels: needs-ok-to-test

#2543 Fearure for #2531 - for eac runtime
  charts/eac/CHANGELOG.md
  charts/eac/templates/fuse/daemonset.yaml
  charts/eac/templates/master/statefulset.yaml
  charts/eac/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#2544 Fearure for #2531 - for thin runtime
  charts/thin/CHANGELOG.md
  charts/thin/Chart.yaml
  charts/thin/templates/fuse/daemonset.yaml
  charts/thin/templates/worker/statefuleset.yaml
Labels: lgtm, needs-ok-to-test, approved

#2574 feature for #2537
  api/v1alpha1/dataset_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/goosefs/transform.go
  pkg/ddc/goosefs/ufs_internal.go
  pkg/ddc/goosefs/ufs_internal_test.go
  pkg/ddc/jindo/transform.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/thin/transform_config.go
  pkg/ddc/thin/transform_fuse.go
  pkg/ddc/thin/transform_fuse_test.go
  pkg/ddc/thin/ufs_internal.go
Labels: lgtm, needs-ok-to-test, approved

#2583 throw error out when the key of mount.Options and EncryptOptions is the same
  docs/en/samples/dataset_sharedOptions.md
  docs/zh/samples/dataset_sharedOptions.md
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/goosefs/ufs_internal.go
  pkg/ddc/thin/ufs_internal.go
Labels: lgtm, needs-ok-to-test, approved

#2587 Update fuse trouble shooting document
  docs/zh/troubleshooting/debug-fuse.md
  docs/zh/userguide/faq.md
Labels: approved

#2546 Fearure for #2531 - for juicefs runtime
  charts/juicefs/CHANGELOG.md
  charts/juicefs/Chart.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
Labels: lgtm, needs-ok-to-test, approved

#2595 fix eac-fuse mount options
  pkg/ddc/eac/transform_option.go
  pkg/ddc/eac/transform_option_test.go
Labels: lgtm, needs-ok-to-test, approved

#2591 [FEATURE] Skip metadata sync for AlluxioRuntime
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/common.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/cache_test.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/alluxio/metadata_test.go
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/thin/transform_fuse_test.go
Labels: lgtm, approved

#2604 add fuse-master image, and update eacruntime version
  charts/eac/CHANGELOG.md
  charts/eac/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#2601 Ignore not found error when unstage volume
  pkg/csi/plugins/nodeserver.go
Labels: lgtm, approved

#2585 support image pull secret for alluxio dataload
  charts/fluid-dataloader/alluxio/templates/dataloader.yaml
  charts/fluid-dataloader/alluxio/values.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  pkg/dataload/value.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/utils.go
  pkg/utils/docker/image.go
  pkg/utils/docker/image_test.go
Labels: lgtm

#2608 Add PVmed to ADOPTERS
  ADOPTERS.md
Labels: needs-ok-to-test, approved

#2598 Combine DataLoadStatus and DataBackupStatus into OperationStatus
  api/v1alpha1/databackup_types.go
  api/v1alpha1/dataload_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  docs/zh/samples/backup_and_restore_metadata.md
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/databackup/constants.go
Labels: lgtm, approved

#2545 Fearure for #2531 - for jindofsx runtime
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/Chart.yaml
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#2625 support image pull secrets for goosefs,jindo,jindofsx,juicefs
  charts/fluid-dataloader/goosefs/templates/dataloader.yaml
  charts/fluid-dataloader/goosefs/values.yaml
  charts/fluid-dataloader/jindo/templates/dataloader.yaml
  charts/fluid-dataloader/jindo/values.yaml
  charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
  charts/fluid-dataloader/jindofsx/values.yaml
  charts/fluid-dataloader/juicefs/templates/dataloader.yaml
  charts/fluid-dataloader/juicefs/values.yaml
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/juicefs/data_load.go
Labels: lgtm, approved

#2628 Fix EACRuntime controller scaling out bug
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/eacruntime_controller.yaml
  charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  pkg/controllers/deploy/runtime_controllers.go
  pkg/ddc/eac/engine.go
  pkg/ddc/factory.go
Labels: lgtm, approved

#2632 Set dataload.status.info as omitEmpty
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/status.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
Labels: lgtm, approved

#2634 Fix rbac for scaling out eacruntime controller
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
Labels: lgtm, approved

#2631 support image pull secrets for databackup
  charts/fluid-databackup/alluxio/templates/databackup.yaml
  charts/fluid-databackup/alluxio/values.yaml
  charts/fluid-databackup/goosefs/templates/databackup.yaml
  charts/fluid-databackup/goosefs/values.yaml
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/databackup/value.go
Labels: lgtm, approved

#2640 Fix eac runtime controller rbac & fix eac.runtime getWorkerPod logic
  charts/fluid/fluid/templates/role/eac/rbac.yaml
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/ddc/eac/data_load.go
  pkg/ddc/eac/node.go
  pkg/ddc/eac/node_test.go
  pkg/ddc/eac/shutdown.go
  pkg/ddc/eac/utils.go
  pkg/ddc/eac/utils_test.go
  pkg/ddc/eac/worker.go
Labels: lgtm, approved

#2642 add addons cubefs_v2.4
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4.md
  addons/cubefs/v2.4/docker/Dockerfile
  addons/cubefs/v2.4/docker/build.sh
  addons/cubefs/v2.4/docker/entrypoint.sh
  addons/cubefs/v2.4/docker/fluid_config_init.py
  addons/cubefs/v2.4/readme-zh_CN.md
  addons/cubefs/v2.4/readme.md
  addons/cubefs/v2.4/runtime-profile.yaml
  addons/readme-zh_CN.md
  addons/readme.md
Labels: needs-ok-to-test

#2644 update addons dev-guide for cubefs 2.4
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
  addons/cubefs/v2.4/readme-zh_CN.md
  addons/cubefs/v2.4/readme.md
  addons/readme-zh_CN.md
Labels: lgtm, needs-ok-to-test, approved

#2650 update ci version
  .github/workflows/codeql-analysis.yml
  .github/workflows/go.yml
Labels: lgtm, approved, ok-to-test

#2656 docs: add leaderboard badge to readme
  README-zh_CN.md
  README.md
Labels: lgtm, needs-ok-to-test, approved

#2651 add dependabot ci
  .github/dependabot.yml
Labels: lgtm, needs-ok-to-test, approved

#2646 Update alpine from 3.16 to 3.17
  addons/nfs/docker/Dockerfile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.eacruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
Labels: lgtm, needs-ok-to-test, approved

#2648 rename dataload constants
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/dataload/constants.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/eac/data_load.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/juicefs/data_load.go
Labels: lgtm, approved

#2663 Fix code format includes comment
  api/v1alpha1/container_network.go
  api/v1alpha1/thinruntimeprofile_types.go
  cmd/goosefs/app/version.go
  cmd/webhook/app/init.go
  cmd/webhook/app/version.go
  pkg/common/constants.go
  pkg/common/fluid_ufs_scheme.go
  pkg/common/label_test.go
  pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
  pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
  pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/alluxio/operations/local.go
  pkg/ddc/base/template_engine.go
  pkg/ddc/goosefs/cache_test.go
  pkg/ddc/goosefs/metadata.go
  pkg/ddc/goosefs/operations/local.go
  pkg/ddc/goosefs/port_parser_test.go
  pkg/ddc/goosefs/runtime_info_test.go
  pkg/ddc/jindo/cache_test.go
  pkg/ddc/jindo/engine_test.go
  pkg/ddc/jindo/operations/base_test.go
  pkg/ddc/jindo/operations/cached_test.go
  pkg/ddc/jindofsx/cache_test.go
  pkg/ddc/jindofsx/engine_test.go
  pkg/ddc/jindofsx/operations/base_test.go
  pkg/ddc/jindofsx/operations/cached_test.go
  pkg/ddc/juicefs/dataset_test.go
  pkg/ddc/juicefs/health_check_test.go
  pkg/ddc/juicefs/metadata.go
  pkg/ddc/juicefs/operations/base_test.go
  pkg/ddc/juicefs/replicas_test.go
  pkg/ddc/thin/metadata.go
  pkg/utils/byte_size.go
  pkg/utils/common.go
  pkg/utils/databackup_test.go
  pkg/utils/dataload_test.go
  pkg/utils/dataset.go
  pkg/utils/dataset_test.go
  pkg/utils/kubeclient/volume.go
  pkg/utils/mountinfo/mountinfo.go
  pkg/utils/time_tracker.go
  pkg/utils/ufs_path_builder.go
  pkg/utils/ufs_path_builder_test.go
  pkg/utils/unix.go
  pkg/utils/webhook.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache.go
  version.go
Labels: lgtm, approved
