Repository fluid-cloudnative/fluid, pull requests merged in 2023-01, with the labels that each got.

#2451 remove redundant logic
  pkg/common/cluster_domain.go
  pkg/common/cluster_domain_test.go
  pkg/ddc/alluxio/master_internal_test.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/types.go
Labels: lgtm, approved

#2489 Fix NPE error when log dataset info
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/goosefs/ufs_internal.go
  pkg/ddc/jindofsx/ufs_internal.go
Labels: lgtm, approved

#2490 DOC: add english doc 'access via rest api'
  docs/en/TOC.md
  docs/en/samples/api_proxy.md
  docs/zh/samples/api_proxy.md
Labels: lgtm, needs-ok-to-test, approved

#2496 Fix Deprecated io/utils
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/csi/recover/recover.go
  pkg/csi/recover/recover_test.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/master_internal.go
  pkg/ddc/eac/master_internal.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/goosefs/master_internal.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindo/master_internal.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/master_internal.go
  pkg/ddc/thin/master_internal.go
  pkg/dump/dump.go
  pkg/utils/charts_test.go
  pkg/utils/helm/helm.go
  pkg/utils/kubectl/configmap.go
  pkg/utils/mount.go
  pkg/utils/mount_test.go
  pkg/utils/webhook/writer/fs.go
  pkg/utils/yaml_test.go
  pkg/webhook/certificate_builder_test.go
  test/e2etest/patch_node_label_test.go
Labels: lgtm

#2491 DOC: add english doc about using go client
  docs/en/TOC.md
  docs/en/dev/use_go_create_resource.md
Labels: needs-ok-to-test, approved

#2501 update fuse container as root user in sidecar mode
  charts/juicefs/CHANGELOG.md
  charts/juicefs/Chart.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
Labels: lgtm, approved

#2499 Fix PVC not cleaned up error
  pkg/utils/dataset/volume/delete.go
  pkg/utils/dataset/volume/delete_test.go
  pkg/utils/kubeclient/volume.go
Labels: lgtm, approved

#2506 add adopters of autelrobotics
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#2505 add e2e test for juicefs
  pkg/controllers/v1alpha1/fluidapp/fluidapp_controller.go
  pkg/controllers/v1alpha1/fluidapp/implement.go
  pkg/controllers/v1alpha1/fluidapp/implement_test.go
  pkg/ctrl/watch/pod.go
  pkg/ctrl/watch/pod_test.go
  pkg/ddc/juicefs/shutdown.go
  test/prow/juicefs_access_data.py
Labels: lgtm, approved

#2509 Juicefs/fix secret key
  charts/juicefs/CHANGELOG.md
  charts/juicefs/Chart.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  charts/juicefs/values.yaml
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/type.go
  test/prow/juicefs_access_data.py
Labels: lgtm, approved

#2510 Unify Fluid controller names
  pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
  pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
Labels: lgtm, approved

#2516 make webhook timeoutSeconds configurable and set default value to 15s
  charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#2518 Enhance ThinRuntime example to follow Dataset specification style in Fluid
  docs/zh/samples/thinruntime.md
Labels: lgtm, approved

#2523 Optimize cleaning cache in runtime
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/common.go
  api/v1alpha1/eacruntime_types.go
  api/v1alpha1/goosefsruntime_types.go
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/juicefsruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_eacruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_eacruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/cache_test.go
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/operations/cached.go
  pkg/ddc/alluxio/operations/cached_test.go
  pkg/ddc/alluxio/shutdown.go
  pkg/ddc/alluxio/shutdown_engine_test.go
  pkg/ddc/alluxio/sync_runtime_test.go
  pkg/ddc/alluxio/transform_optimization_test.go
  pkg/ddc/alluxio/transform_test.go
  pkg/ddc/alluxio/utils_test.go
Labels: approved

#2528 docs: add coScene adopter
  ADOPTERS.md
Labels: needs-ok-to-test

#2529 Set default value for clean cache
  api/v1alpha1/common.go
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_eacruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  charts/fluid/fluid/values.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_eacruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  pkg/ddc/alluxio/cache_test.go
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/shutdown.go
  samples/accelerate/dataset.yaml
Labels: lgtm, approved

#2535 Add EAC Fuse to pruneFS to avoid mlocate scan
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2536 [BUGFIX] Support recovery from metadata sync channel panics
  pkg/ddc/alluxio/cache_test.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/alluxio/metadata_test.go
  pkg/ddc/alluxio/shutdown.go
  pkg/ddc/alluxio/transform_optimization_test.go
  pkg/ddc/alluxio/transform_test.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/base/metadata_sync.go
  pkg/ddc/base/metadata_sync_test.go
  pkg/ddc/goosefs/engine.go
  pkg/ddc/goosefs/metadata.go
  pkg/ddc/goosefs/transform_optimization_test.go
  pkg/ddc/goosefs/ufs_test.go
  pkg/ddc/jindo/engine.go
  pkg/ddc/jindo/metadata.go
  pkg/ddc/jindo/metadata_test.go
  pkg/ddc/jindofsx/engine.go
  pkg/ddc/jindofsx/metadata.go
  pkg/ddc/jindofsx/metadata_test.go
  pkg/ddc/juicefs/engine.go
  pkg/ddc/juicefs/metadata.go
  pkg/ddc/juicefs/metadata_test.go
  pkg/ddc/thin/engine.go
  pkg/ddc/thin/metadata.go
  pkg/ddc/thin/metadata_test.go
Labels: lgtm, approved
