Repository fluid-cloudnative/fluid, pull requests merged in 2023-12, with the labels that each got.

#3589 docs: fix 命名空间
  docs/zh/samples/dataset_across_namespace_with_csi.md
  docs/zh/samples/dataset_across_namespace_with_sidecar.md
  docs/zh/samples/dataset_mount_dataset_subpath.md
Labels: lgtm, needs-ok-to-test, approved

#3574 modify pkg/ddc/jindofsx/operate.go
  pkg/ddc/jindofsx/operate.go
Labels: lgtm, needs-ok-to-test, approved

#3595 add license for exec.go
  pkg/utils/kubeclient/exec.go
Labels: lgtm, needs-ok-to-test, approved

#3545 support webhook mutating plugins configurable
  charts/fluid/fluid/templates/webhook/plugins-profile.yaml
  charts/fluid/fluid/templates/webhook/tiered-conf.yaml
  charts/fluid/fluid/values.yaml
  cmd/webhook/app/webhook.go
  pkg/common/constants.go
  pkg/common/webhook.go
  pkg/webhook/plugins/api/plugins_api.go
  pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
  pkg/webhook/plugins/fusesidecar/fuse_sidecar_test.go
  pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector.go
  pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector_test.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache_test.go
  pkg/webhook/plugins/plugins.go
  pkg/webhook/plugins/plugins_configmap.go
  pkg/webhook/plugins/plugins_impl.go
  pkg/webhook/plugins/plugins_impl_test.go
  pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache.go
  pkg/webhook/plugins/prefernodeswithoutcache/prefer_nodes_without_cache_test.go
  pkg/webhook/plugins/requirenodewithfuse/require_node_with_fuse.go
  pkg/webhook/plugins/requirenodewithfuse/require_node_with_fuse_test.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
Labels: lgtm, approved

#3579 This pr is to add license in pkg/ddc/efc/data_process_test.go.
  pkg/ddc/efc/data_process_test.go
Labels: lgtm, needs-ok-to-test, approved

#3602 change Author to Authors in pkg/utils/kubeclient/deployment.go
  pkg/utils/kubeclient/deployment.go
Labels: lgtm, needs-ok-to-test, approved

#3628 webhook use configmap volume mount instead of api query
  charts/fluid/fluid/templates/webhook/webhook.yaml
  cmd/webhook/app/webhook.go
  docs/en/operation/tiered_locality_schedule.md
  docs/zh/operation/tiered_locality_schedule.md
  pkg/common/webhook.go
  pkg/webhook/plugins/plugins_impl.go
  pkg/webhook/plugins/plugins_impl_test.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
  test/prow/testcases/common/webhook_mutating.py
Labels: lgtm, approved

#3587 fix License in pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/load_data.go
Labels: lgtm, needs-ok-to-test, approved

#3632 enhance: remove jindoruntime's fsGroup
  charts/jindocache/CHANGELOG.md
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/templates/worker/statefulset.yaml
  charts/jindocache/values.yaml
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
  charts/jindofsx/values.yaml
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/types.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/types.go
Labels: lgtm, approved

#3634 enhance: Mount ufs volumes according to datasets' accessModes
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindofsx/transform.go
Labels: lgtm, approved

#3640 Fix typos in using Go client document
  docs/en/dev/use_go_create_resource.md
  docs/zh/dev/use_go_create_resource.md
Labels: lgtm, needs-ok-to-test, approved

#3621 Feature: add GlusterFS addons
  addons/glusterfs/dev-guide/glusterfs-zh_CN.md
  addons/glusterfs/dev-guide/glusterfs.md
  addons/glusterfs/docker/Dockerfile
  addons/glusterfs/docker/build.sh
  addons/glusterfs/docker/entrypoint.py
  addons/glusterfs/readme-zh_CN.md
  addons/glusterfs/readme.md
  addons/glusterfs/runtime-profile.yaml
Labels: lgtm, needs-ok-to-test, approved

#3641 enhance: remove jindoruntime's fsGroup (#3632)
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
  charts/jindofsx/values.yaml
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/types.go
Labels: lgtm, approved

#3642 Temporarily remove webhook plugins for serverless
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3643 Add JoinQuant as a new adopter
  ADOPTERS.md
Labels: needs-ok-to-test, approved

#3644 docs: apply fluid to production
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#3596 modify pkg/utils/ufs_path_builder_test.go from 'Author' to 'Authors'
  pkg/utils/ufs_path_builder_test.go
Labels: needs-ok-to-test, approved

#3635 Remove fsgroup from alluxio runtime
  charts/alluxio/CHANGELOG.md
  charts/alluxio/Chart.yaml
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
  charts/alluxio/values.yaml
  charts/fluid-databackup/alluxio/templates/databackup.yaml
  charts/fluid-databackup/alluxio/values.yaml
  charts/fluid-databackup/goosefs/templates/databackup.yaml
  pkg/ddc/alluxio/backup_data.go
  pkg/ddc/alluxio/port_parser_test.go
  pkg/ddc/alluxio/transform.go
Labels: lgtm, approved

#3514 Update recover_test.go Copyright Year to 2022
  pkg/csi/recover/recover_test.go
Labels: lgtm, needs-ok-to-test, approved

#3652 docs: apply fluid to production
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#3651 Docker build for fixing fsgroup issue
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3658 Fix Alluxio master in HA mode start error.
  charts/alluxio/templates/master/statefulset.yaml
  pkg/ddc/alluxio/ufs.go
  pkg/ddc/alluxio/ufs_test.go
Labels: lgtm, approved

#3624 Add the helm chart for vineyard runtime.
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  charts/alluxio/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/vineyard/Chart.yaml
  charts/vineyard/templates/_helpers.tpl
  charts/vineyard/templates/config/vineyard-rpc-conf.yaml
  charts/vineyard/templates/fuse/daemonset.yaml
  charts/vineyard/templates/master/service.yaml
  charts/vineyard/templates/master/statefulset.yaml
  charts/vineyard/templates/worker/service.yaml
  charts/vineyard/templates/worker/statefulset.yaml
  charts/vineyard/values.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
Labels: lgtm, needs-ok-to-test, approved

#3662 fix jindocache dataloader
  charts/fluid-dataloader/jindocache/templates/job.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
Labels: lgtm, approved

#3663 Add roadmap for 2022
  ROADMAP.md
Labels: lgtm, approved

#3664 Support Parallel podManagementPolicy for AlluxioRuntime HA Master
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/values.yaml
Labels: lgtm, approved

#3657 Validate the env variable MOUNT_ROOT
  pkg/utils/mount.go
  pkg/utils/mount_test.go
  pkg/utils/validation/validation.go
  pkg/utils/validation/validation_test.go
Labels: lgtm, needs-ok-to-test, approved

#3661 Build docker images for alluxio HA
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3665 upgrade jindocache to 6.2.0 and support forceload
  charts/fluid-dataloader/jindocache/CHANGELOG.md
  charts/fluid-dataloader/jindocache/templates/configmap.yaml
  charts/fluid-dataloader/jindocache/templates/job.yaml
  charts/jindocache/Chart.yaml
  charts/jindocache/values.yaml
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_fuse_test.go
  pkg/ddc/jindocache/transform_test.go
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#3655 Update api docs
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
Labels: lgtm, approved

#3666 Add Journal Paper Information into Readme
  README-zh_CN.md
  README.md
Labels: lgtm, approved

#3669 Create roadmap for 2023
  ROADMAP.md
Labels: lgtm, approved

#3659 Add the controller and rbac yaml for vineyard runtime.
  charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
  charts/fluid/fluid/templates/role/csi/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/vineyard/rbac.yaml
  charts/fluid/fluid/templates/role/webhook/rabc.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#3670 fix support readCacheReplica and writeCacheReplica with jindoruntime
  charts/jindocache/templates/config/jindofs-conf.yaml
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_test.go
  pkg/ddc/jindocache/types.go
Labels: lgtm, approved

#3613 Normalize license format in pkg/ddc/jindocache/engine_test.go
  pkg/ddc/jindocache/engine_test.go
Labels: lgtm, needs-ok-to-test, approved
