Repository fluid-cloudnative/fluid, pull requests merged in 2023-03, with the labels that each got.

#2637 Use OperationRef instead of DataloadRef and DataBackupRef
  api/v1alpha1/dataset_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/databackup/constants.go
  pkg/dataload/constants.go
  pkg/utils/databackup.go
  pkg/utils/databackup_test.go
  pkg/utils/dataload.go
  pkg/utils/dataload_test.go
Labels: lgtm, approved

#2669 allocate metrics port for multi runtime
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  charts/juicefs/values.yaml
  cmd/juicefs/app/juicefs.go
  pkg/ddc/jindo/types.go
  pkg/ddc/juicefs/const.go
  pkg/ddc/juicefs/data_load_test.go
  pkg/ddc/juicefs/master_internal_test.go
  pkg/ddc/juicefs/port_parser.go
  pkg/ddc/juicefs/port_parser_test.go
  pkg/ddc/juicefs/shutdown.go
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/juicefs/transform_test.go
  pkg/ddc/juicefs/type.go
  pkg/ddc/juicefs/utils.go
  pkg/ddc/juicefs/utils_test.go
Labels: lgtm, approved

#2683 enhance datamigrate crd shortname
  api/v1alpha1/datamigrate_types.go
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  pkg/ddc/juicefs/data_load.go
Labels: lgtm, approved

#2689 Fix alluxio shutdown unit test
  go.mod
  go.sum
  pkg/ddc/alluxio/shutdown_engine_test.go
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/modules.txt
Labels: lgtm, approved

#2687 NFS fuse
  addons/nfs/dev-guide/nfs-zh_CN.md
  addons/nfs/dev-guide/nfs.md
  addons/nfs/docker/Dockerfile
  addons/nfs/docker/fluid_config_init.py
  addons/nfs/readme-zh_CN.md
  addons/nfs/readme.md
Labels: needs-ok-to-test, approved

#2672 update migrateRef to operateRef
  api/v1alpha1/dataset_types.go
  api/v1alpha1/openapi_generated.go
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/datamigrate/constants.go
Labels: lgtm, approved

#2691 Build docker images for operateRef
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2649 Feat/dataload support affinity
  api/v1alpha1/dataload_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-dataloader/alluxio/CHANGELOG.md
  charts/fluid-dataloader/alluxio/templates/dataloader.yaml
  charts/fluid-dataloader/alluxio/values.yaml
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/dataload/value.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindofsx/load_data.go
Labels: lgtm, approved

#2693 Update get started doc
  docs/en/userguide/get_started.md
  docs/zh/userguide/get_started.md
Labels: lgtm, approved

#2697 Regulate RBAC of Fluid controllers
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/eac/rbac.yaml
  charts/fluid/fluid/templates/role/goosefs/rbac.yaml
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/fluid/fluid/templates/role/thin/rbac.yaml
Labels: lgtm, approved

#2690 update addons for cubefs 2.4 to not use cubefs csi
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4.md
  addons/cubefs/v2.4/docker/fluid_config_init.py
  addons/cubefs/v2.4/readme-zh_CN.md
  addons/cubefs/v2.4/readme.md
Labels: lgtm, approved, ok-to-test

#2692 Feat/dataload support affinity docs cn
  docs/zh/samples/data_warmup.md
Labels: lgtm, approved

#2703 [Enhancement]CSI plugin checks mount point liveness before binding mount points
  csi/shell/check_mount.sh
  pkg/csi/plugins/nodeserver.go
Labels: lgtm, approved

#2702 Support setting webhook reinvocationPolicy in chart
  charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#2686 Add Sonarcloud Scan ci
  .github/workflows/sonarcloud.yaml
  sonar-project.properties
Labels: lgtm, approved

#2705 Remove deprecated serviceAccount
  charts/fluid/fluid/templates/csi/daemonset.yaml
  csi/deploy/csi-fluid-provisioner.yaml
  integration/cronhpa/deploy.yaml
  integration/prometheus/prometheus-goosefs.yaml
  integration/prometheus/prometheus-jindofs.yaml
  integration/prometheus/prometheus.yaml
Labels: lgtm, approved

#2708 Update circleci image circleci/golang:1.17 to cimg/go:1.18
  .circleci/config.yml
Labels: lgtm, approved

#2678 Datatable2
  api/v1alpha1/datatable_types.go
  charts/fluid/fluid/crds/data.fluid.io_datatables.yaml
  config/crd/bases/data.fluid.io_datatables.yaml
  go.mod
  go.sum
  pkg/controllers/v1alpha1/datatable/datatable_controller.go
  pkg/utils/hive/hive.go
  vendor/git.apache.org/thrift.git/LICENSE
  vendor/git.apache.org/thrift.git/NOTICE
  vendor/git.apache.org/thrift.git/lib/go/thrift/application_exception.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/binary_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/buffered_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/client.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/compact_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/context.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/debug_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/deserializer.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/exception.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/field.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/framed_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/http_client.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/http_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/iostream_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/json_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/memory_buffer.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/messagetype.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/multiplexed_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/numeric.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/pointerize.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/processor_factory.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/protocol_exception.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/protocol_factory.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/rich_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/serializer.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/server.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/server_socket.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/server_transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/simple_json_protocol.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/simple_server.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/socket.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/ssl_server_socket.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/ssl_socket.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/transport.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/transport_exception.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/transport_factory.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/type.go
  vendor/git.apache.org/thrift.git/lib/go/thrift/zlib_transport.go
  vendor/github.com/dazheng/gohive/.gitattributes
  vendor/github.com/dazheng/gohive/connection.go
  vendor/github.com/dazheng/gohive/inf/GoUnusedProtection__.go
  vendor/github.com/dazheng/gohive/inf/inf-consts.go
  vendor/github.com/dazheng/gohive/inf/inf.go
  vendor/github.com/dazheng/gohive/inf/inf.thrift
  vendor/github.com/dazheng/gohive/readme.md
  vendor/github.com/dazheng/gohive/rowset.go
  vendor/modules.txt
Labels: lgtm, needs-ok-to-test, approved

#2720 Fix permission issue which is introduced by circleci
  .circleci/config.yml
Labels: lgtm, approved

#2718 Prettify error messages for exec.Commands in Fluid
  pkg/csi/plugins/nodeserver.go
  pkg/utils/helm/utils.go
  pkg/utils/mount.go
Labels: lgtm, approved

#2700 Add specify namespace installation
  charts/fluid/fluid/templates/_helpers.tpl
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/eacruntime_controller.yaml
  charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
  charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  charts/fluid/fluid/templates/csi/daemonset.yaml
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/csi/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/eac/rbac.yaml
  charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
  charts/fluid/fluid/templates/role/goosefs/rbac.yaml
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/fluid/fluid/templates/role/thin/rbac.yaml
  charts/fluid/fluid/templates/role/webhook/rabc.yaml
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
  charts/fluid/fluid/templates/webhook/service.yaml
  charts/fluid/fluid/templates/webhook/webhook.yaml
  charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
  charts/fluid/fluid/values.yaml
  pkg/controllers/deploy/runtime_controllers.go
Labels: lgtm, approved

#2728 support setting affinity when using GooseFS Dataload
  charts/fluid-dataloader/goosefs/CHANGELOG.md
  charts/fluid-dataloader/goosefs/templates/dataloader.yaml
  charts/fluid-dataloader/goosefs/values.yaml
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/goosefs/load_data_test.go
Labels: lgtm, approved

#2727 Build docker images for customizing management namespace
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2716 Optimize pod filter implementation in webhook
  pkg/common/constants.go
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/worker.go
  pkg/ddc/eac/const.go
  pkg/ddc/eac/worker.go
  pkg/ddc/goosefs/const.go
  pkg/ddc/goosefs/worker.go
  pkg/ddc/jindo/const.go
  pkg/ddc/jindo/worker.go
  pkg/ddc/jindofsx/const.go
  pkg/ddc/jindofsx/worker.go
  pkg/ddc/juicefs/const.go
  pkg/ddc/juicefs/worker.go
  pkg/ddc/thin/const.go
  pkg/ddc/thin/node.go
  pkg/ddc/thin/worker.go
  pkg/utils/fluid.go
  pkg/utils/fluid_test.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
Labels: lgtm, approved

#2724 Forget prometheus metrics after shutting down engines
  pkg/controllers/runtime_controller.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/base/metadata_sync.go
  pkg/ddc/base/setup.go
  pkg/ddc/base/syncs.go
  pkg/ddc/base/template_engine.go
  pkg/ddc/jindofsx/metadata.go
  pkg/ddc/juicefs/metadata.go
  pkg/ddc/thin/metadata.go
  pkg/metrics/dataset_metrics.go
  pkg/metrics/labels_key_func.go
  pkg/metrics/runtime_metrics.go
Labels: lgtm, approved

#2715 Update golang:1.17.8 to golang:1.18
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.eacruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
Labels: lgtm, approved

#2736 Remove the from platform parameter to support docker build
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.eacruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
Labels: lgtm, approved

#2739 update mount to check mountinfo
  csi/shell/check_bind_mounts.sh
  csi/shell/check_mount.sh
  pkg/scripts/poststart/check_fuse.go
  pkg/scripts/poststart/check_fuse_app.go
Labels: lgtm, approved

#2742 Lower termination grace period seconds of EACRuntime
  charts/eac/templates/fuse/daemonset.yaml
  charts/eac/templates/master/statefulset.yaml
Labels: lgtm, approved

#2729 support setting affinity when using Jindo Dataload
  charts/fluid-dataloader/jindo/CHANGELOG.md
  charts/fluid-dataloader/jindo/templates/dataloader.yaml
  charts/fluid-dataloader/jindo/values.yaml
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindo/load_data_test.go
Labels: lgtm, approved

#2744 Refactor EAC SessMgr
  charts/eac/templates/fuse/daemonset.yaml
  charts/fluid/fluid/templates/role/eac/rbac.yaml
  cmd/eac/app/eac.go
  pkg/common/eac.go
  pkg/csi/plugins/nodeserver.go
  pkg/ddc/eac/create_volume.go
  pkg/ddc/eac/create_volume_test.go
  pkg/ddc/eac/sessmgr.go
Labels: lgtm, approved

#2743 Add Report Vulnerability info
  README-zh_CN.md
  README.md
Labels: lgtm, approved

#2756 Add weiwei to approver list
  OWNERS
Labels: lgtm, approved

#2754 Skip sonar analysis for test.go file
  sonar-project.properties
Labels: lgtm, approved

#2747 Fix CSI FUSE Recovery
  pkg/csi/recover/recover.go
  pkg/csi/recover/recover_test.go
Labels: lgtm, approved

#2765 Grant secret update permission to Fluid controllers
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/eac/rbac.yaml
  charts/fluid/fluid/templates/role/goosefs/rbac.yaml
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/fluid/fluid/templates/role/thin/rbac.yaml
Labels: lgtm, approved

#2766 fix port allocate
  pkg/ddc/juicefs/transform.go
Labels: lgtm, approved

#2751 [BUGFIX] Fix unexpected dataset phase after helm install failure
  pkg/utils/helm/utils.go
Labels: lgtm, approved

#2761 support setting affinity when using JuiceFS Dataload
  charts/fluid-dataloader/juicefs/CHANGELOG.md
  charts/fluid-dataloader/juicefs/templates/dataloader.yaml
  charts/fluid-dataloader/juicefs/values.yaml
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_load_test.go
Labels: lgtm, approved

#2753 Update docker image of csi-node-driver-registrar
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2767 Fix code smells of dockerfile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.eacruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
  sonar-project.properties
Labels: lgtm, approved

#2769 Update adopters
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#2477 add e2e testcase fuse-recovery
  test/prow/fuse_recovery.py
Labels: lgtm, needs-ok-to-test, approved

#2773 fix(alluxio): should use json tag instead of yaml tag
  pkg/ddc/alluxio/types_selector.go
Labels: lgtm, needs-ok-to-test, approved

#2759 support setting affinity when using JindoFSX Dataload
  charts/fluid-dataloader/jindofsx/CHANGELOG.md
  charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
  charts/fluid-dataloader/jindofsx/values.yaml
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/jindofsx/load_data_test.go
Labels: lgtm, approved

#2712 refactor DataBackupReconcile to use DataOperationReconcile
  api/v1alpha1/dataset_types.go
  pkg/common/constants.go
  pkg/controllers/operation_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller_test.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/databackup/constants.go
  pkg/dataoperation/context.go
  pkg/dataoperation/interface.go
  pkg/ddc/alluxio/backup_data.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/base/engine.go
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/operation.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/base/operation_lock_test.go
  pkg/ddc/base/runtime.go
  pkg/ddc/eac/operate.go
  pkg/ddc/goosefs/backup_data.go
  pkg/ddc/goosefs/operate.go
  pkg/ddc/jindo/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/operate.go
  pkg/ddc/thin/referencedataset/engine.go
  pkg/errors/errors_test.go
  pkg/errors/notsupported.go
  pkg/utils/common.go
  pkg/utils/crtl_utils.go
  pkg/utils/databackup.go
  pkg/utils/databackup_test.go
  pkg/utils/kubeclient/pod.go
Labels: lgtm, approved

#2711 Prow: refactor fluid e2e framework and rewrite testcases
  .gitignore
  test/prow/access_oss_via_jindorumtime.py
  test/prow/access_web_ufs.py
  test/prow/alluxio_dynamic_mountpoint.py
  test/prow/alluxioruntime_resources_setting.py
  test/prow/csi_stable_patch.py
  test/prow/fluid/fluidapi.py
  test/prow/fluid/step_funcs.py
  test/prow/framework/exception.py
  test/prow/framework/step.py
  test/prow/framework/testflow.py
  test/prow/fuse_recovery.py
  test/prow/juicefs_access_data.py
  test/prow/patch_node_label_parallel.py
  test/prow/testcases/alluxio/alluxio_dynamic_mountpoint.py
  test/prow/testcases/alluxio/alluxio_webufs.py
  test/prow/testcases/alluxio/alluxio_webufs_set_resources.py
  test/prow/testcases/common/csi_stale_patch.py
  test/prow/testcases/common/fuse_recovery.py
  test/prow/testcases/common/patch_node_label_parallel.py
  test/prow/testcases/jindofsx/jindo_oss.py
  test/prow/testcases/juicefs/juicefs_minio.py
  test/prow/testcases/juicefs/juicefs_minio_sidecar.py
Labels: lgtm, approved

#2776 Fix license in file pkg/csi/updatedbconf/updatedbconf.go
  pkg/csi/updatedbconf/updatedbconf.go
Labels: lgtm, needs-ok-to-test, approved

#2783 Build docker images for refactoring operations
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2782 Fix license issue in pkg/ddc/jindo/operations/cached.go
  pkg/ddc/jindo/operations/cached.go
Labels: lgtm, needs-ok-to-test, approved

#2777 feat: support metadataList in runtime
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/common.go
  api/v1alpha1/eacruntime_types.go
  api/v1alpha1/goosefsruntime_types.go
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/juicefsruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/thinruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_eacruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_eacruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/runtime.go
  pkg/ddc/thin/referencedataset/runtime.go
  pkg/utils/dataset/volume/create.go
Labels: lgtm, needs-ok-to-test, approved

#2789 add copyright
  pkg/ddc/alluxio/runtime_info.go
Labels: lgtm, needs-ok-to-test, approved

#2784 add cephfs thinruntime
  addons/cephfs/dev-guide/cephfs-zh_CN.md
  addons/cephfs/dev-guide/cephfs.md
  addons/cephfs/docker/Dockerfile
  addons/cephfs/docker/build.sh
  addons/cephfs/docker/entrypoint.sh
  addons/cephfs/docker/fluid_config_init.py
  addons/cephfs/readme-zh_CN.md
  addons/cephfs/readme.md
  addons/cephfs/runtime-profile.yaml
Labels: lgtm, approved

#2790 added License description
  pkg/ddc/alluxio/operations/conf.go
Labels: lgtm, needs-ok-to-test, approved

#2791 add License description
  pkg/ddc/thin/wrap_pvc_test.go
Labels: lgtm, needs-ok-to-test, approved

#2795 add Copyright
  pkg/runtime/context.go
Labels: lgtm, needs-ok-to-test, approved

#2785 Cherry pick for 0.8.5
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  charts/juicefs/CHANGELOG.md
  charts/juicefs/Chart.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  csi/shell/check_mount.sh
  docs/zh/samples/juicefs/juicefs_cache_dir.md
  docs/zh/samples/juicefs/juicefs_for_s3.md
  docs/zh/samples/juicefs/juicefs_runtime.md
  docs/zh/samples/juicefs/juicefs_setup.md
  pkg/csi/plugins/nodeserver.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/juicefs/operations/base_test.go
  pkg/ddc/juicefs/shutdown.go
  pkg/ddc/juicefs/shutdown_test.go
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_volume.go
  pkg/ddc/juicefs/transform_volume_test.go
  pkg/ddc/juicefs/utils_test.go
  pkg/scripts/poststart/check_fuse.go
  pkg/utils/helm/utils.go
  pkg/utils/mount.go
  test/prow/juicefs_access_data.py
Labels: lgtm

#2804 add Apache License to pkg/ddc/base/metadata_sync_test.go
  pkg/ddc/base/metadata_sync_test.go
Labels: lgtm, needs-ok-to-test, approved

#2798 add copyright to file 'fluid/pkg/util/unix.go'
  pkg/utils/unix.go
Labels: lgtm, needs-ok-to-test, approved

#2801 add Copyright
  pkg/ddc/alluxio/transform_permission_test.go
Labels: lgtm, needs-ok-to-test, approved

#2805 add apache license to `pkg/ddc/goosefs/dataset_test.go`
  pkg/ddc/goosefs/dataset_test.go
Labels: lgtm, needs-ok-to-test, approved

#2808 Add the Apache License
  pkg/utils/capabilities_test.go
Labels: lgtm, needs-ok-to-test, approved

#2807 add Apache License
  pkg/ddc/juicefs/data_load_test.go
Labels: lgtm, needs-ok-to-test, approved

#2816 BUGFIX: fix init-fuse container privilege mode for EAC SessMgr
  pkg/ddc/eac/sessmgr.go
Labels: lgtm, approved

#2821 Build docker images for fixing init-fuse init container privileged mo…
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#2811 Add Apache License
  pkg/ddc/thin/transform_pvc_mounts.go
Labels: lgtm, needs-ok-to-test, approved
