Repository fluid-cloudnative/fluid, pull requests merged in 2023-05, with the labels that each got.

#3185 Lab1 Task2
  pkg/utils/helm/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#3186 normalize Apache License on pkg/controllers/v1alpha1/efc/efcruntime_c…
  pkg/controllers/v1alpha1/efc/efcruntime_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3196 doc: add guide to debug webhook locally
  docs/en/dev/how_to_develop.md
  docs/zh/dev/how_to_develop.md
Labels: lgtm, needs-ok-to-test, approved

#3189 task180 finished by chengchen
  pkg/utils/kubeclient/secret.go
Labels: lgtm, needs-ok-to-test, approved

#3200 Refactor efc images
  charts/efc/templates/fuse/daemonset.yaml
  charts/efc/templates/master/statefulset.yaml
  charts/efc/templates/worker/statefulset.yaml
  charts/efc/values.yaml
  charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
  charts/fluid/fluid/values.yaml
  docs/zh/samples/efc_runtime.md
  docs/zh/troubleshooting/debug-fuse.md
  pkg/common/efc.go
  pkg/ddc/efc/const.go
  pkg/ddc/efc/master_internal_test.go
  pkg/ddc/efc/sessmgr.go
  pkg/ddc/efc/transform.go
  pkg/ddc/efc/transform_image.go
  pkg/ddc/efc/transform_image_test.go
  pkg/ddc/efc/transform_option.go
  pkg/ddc/efc/transform_option_test.go
  pkg/ddc/efc/transform_test.go
  pkg/ddc/efc/types.go
  pkg/ddc/efc/ufs_test.go
  pkg/ddc/efc/utils.go
  pkg/ddc/efc/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#3146 feat: move metadata list to annotation
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/efcruntime_types.go
  api/v1alpha1/goosefsruntime_types.go
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/juicefsruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/thinruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_efcruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_efcruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/ddc/alluxio/runtime_info.go
  pkg/ddc/base/runtime.go
  pkg/ddc/efc/runtime_info.go
  pkg/ddc/goosefs/runtime_info.go
  pkg/ddc/jindo/runtime_info.go
  pkg/ddc/jindofsx/runtime_info.go
  pkg/ddc/juicefs/runtime_info.go
  pkg/ddc/thin/referencedataset/runtime.go
  pkg/ddc/thin/runtime_info.go
Labels: lgtm, needs-ok-to-test, approved

#3204 Docker build for removing metadatalist from runtime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  pkg/utils/kubeclient/node_test.go
Labels: lgtm, approved

#3206 efcruntime remove unreasonable config to support eci features
  charts/efc/templates/fuse/daemonset.yaml
  charts/efc/templates/master/statefulset.yaml
  charts/efc/templates/worker/statefulset.yaml
  charts/fluid/fluid/values.yaml
  pkg/ddc/efc/sessmgr.go
Labels: lgtm, needs-ok-to-test, approved

#3207 Trim efc-sock volume for fuse sidecar injection
  pkg/ddc/base/runtime_helper.go
Labels: lgtm, approved

#3208 Update docker images for efcruntime on serverless container
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3213 Build docker images for fixing CSI Plugin's node related access
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3216 fix(efcruntime): remove init container and sessmgr in efc-master yaml
  charts/efc/templates/master/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#3217 fix(efcruntime): Add runtime identity info and fix readiness probe for EFCRuntime
  charts/efc/templates/fuse/daemonset.yaml
  charts/efc/values.yaml
  pkg/ddc/efc/transform.go
  pkg/ddc/efc/types.go
Labels: lgtm, approved

#3219 Set default webhook reinvocationPolicy to IfNeeded
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#3221 fix(efcruntime): set Privileged=true when init-fuse start
  pkg/ddc/efc/sessmgr.go
Labels: lgtm, needs-ok-to-test, approved

#3225 Build docker images for default reinvocationPolicy as IfNeeded
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3039 add e2e test to validate dataset using pvc subpath
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
  charts/goosefs/templates/master/statefulset.yaml
  charts/goosefs/templates/worker/statefulset.yaml
  test/prow/testcases/common/dataset_pvc_subpath.py
Labels: lgtm, needs-ok-to-test, approved

#3223 Update to 0.8.7
  Makefile
  charts/fluid/fluid/Chart.yaml
Labels: lgtm, approved

#3214 update helm to 3.11.3
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
Labels: lgtm, needs-ok-to-test, approved

#3229 fix(efcruntime): add prefix efc to /dev/shm volume when eci
  charts/efc/templates/fuse/daemonset.yaml
Labels: lgtm, needs-ok-to-test, approved

#3226 Change reinvocationPolicy to IfNeeded
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/templates/webhook/webhookconfiguration.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3231 Cherry-pick bugfix for setting fuse args when using Alluxio 2.8+
  pkg/ddc/alluxio/transform_fuse_test.go
  pkg/ddc/alluxio/transform_optimization.go
  pkg/ddc/alluxio/transform_optimization_test.go
Labels: lgtm, approved

#3232 Build docker images for removing secret in jindoruntime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3233 Build docker images for jindoruntime secret mount enhancement
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3202 Integrate with KServe
  integration/kserve/kserve-runtimes.yaml
  integration/kserve/kserve.yaml
Labels: lgtm, approved

#3235 Adapt to libfuse 3
  pkg/ddc/alluxio/transform_fuse_test.go
  pkg/ddc/alluxio/transform_optimization.go
  pkg/ddc/alluxio/transform_optimization_test.go
  pkg/ddc/alluxio/transform_test.go
Labels: lgtm, needs-ok-to-test, approved

#3236 Build docker images: libfuse3 for alluxio 2.9
  Makefile
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3240 bugfix: Set Dataset.Spec.Mounts as a required property
  api/v1alpha1/dataset_types.go
  api/v1alpha1/openapi_generated.go
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
Labels: lgtm, approved

#3241 fix trun off metrics port with jindofuse
  pkg/ddc/jindofsx/transform.go
Labels: lgtm

#3246 optimize: optimize makefile targets and speed up docker build
  .github/workflows/go.yml
  Makefile
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.efcruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
  test/prow/testcases/common/fuse_recovery.py
Labels: lgtm, approved

#3247 Update architecture
  static/architecture.png
Labels: lgtm, approved

#3244 Build docker images for metrics port
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3249 Prepare release 0.9
  CHANGELOG.md
  README-zh_CN.md
  README.md
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  docs/en/userguide/install.md
  docs/zh/userguide/install.md
Labels: lgtm, approved

#3252 bugfix: fix jindo-fuse postStart script to make sure fuse mountpoint is ready
  pkg/scripts/poststart/check_fuse.go
  test/prow/testcases/jindofsx/jindo_oss.py
  test/prow/testcases/jindofsx/jindo_oss_fusesidecar.py
Labels: lgtm, approved

#3253 Build docker image for 0.9.0
  README-zh_CN.md
  README.md
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3254 Update alpine 3.17 to 3.18
  addons/cephfs/dev-guide/cephfs-zh_CN.md
  addons/cephfs/dev-guide/cephfs.md
  addons/cephfs/docker/Dockerfile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.webhook
Labels: lgtm, approved

#3256 Prepare docker image for alpine 3.18
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3251 fix support dataload with filter and upgrade to 4.6.8 for jindoruntime
  charts/fluid-dataloader/jindofsx/templates/configmap.yaml
  charts/fluid-dataloader/jindofsx/templates/dataloader.yaml
  charts/fluid/fluid/values.yaml
  charts/fluid/v0.8.0/values.yaml
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/Chart.yaml
  charts/jindofsx/values.yaml
  pkg/ddc/jindofsx/const.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/transform_fuse_test.go
  pkg/ddc/jindofsx/transform_test.go
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#3245 del lock of dataset in data operate
  api/v1alpha1/dataset_types.go
  api/v1alpha1/dataset_types_test.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/base/operation_lock_test.go
Labels: lgtm, approved
