Repository fluid-cloudnative/fluid, pull requests merged in 2023-11, with the labels that each got.

#3506 Modify the License of shutdown.go
  pkg/ddc/goosefs/shutdown.go
Labels: lgtm, needs-ok-to-test, approved

#3502 Refactor OperationReconcilerInterface to remove type assertions
  pkg/controllers/operation_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/databackup/status_handler.go
  pkg/controllers/v1alpha1/databackup/status_handler_test.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/dataload/status_handler.go
  pkg/controllers/v1alpha1/dataload/status_handler_test.go
  pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
  pkg/controllers/v1alpha1/dataprocess/dataprocess_controller.go
  pkg/controllers/v1alpha1/dataprocess/implement.go
  pkg/controllers/v1alpha1/dataprocess/status_handler.go
  pkg/controllers/v1alpha1/dataprocess/status_handler_test.go
  pkg/dataoperation/interface.go
  pkg/dataoperation/mock.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/base/engine.go
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/operation.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/efc/operate.go
  pkg/ddc/goosefs/operate.go
  pkg/ddc/jindo/operate.go
  pkg/ddc/jindocache/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/operate.go
  pkg/ddc/thin/referencedataset/engine.go
  pkg/utils/datamigrate.go
  pkg/utils/datamigrate_test.go
  pkg/utils/dataoperation.go
  pkg/utils/dataoperation_test.go
Labels: lgtm, approved

#3508 Modify the License of fluid\pkg\ddc\goosefs
  pkg/ddc/goosefs/replicas.go
Labels: lgtm, needs-ok-to-test, approved

#3513 add a flag to control whether update the tiered locality configmap content or not
  charts/fluid/fluid/templates/webhook/tiered-conf.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3511 modify the license of pkg/ddc/jindo/operate.go
  pkg/ddc/jindo/operate.go
Labels: lgtm, needs-ok-to-test, approved

#3519 Build docker images for tiered scheduling
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3512 update YEAR of the license text of pkg/dataoperation/context.go
  pkg/dataoperation/context.go
Labels: lgtm, needs-ok-to-test, approved

#3522 PR: docs: added Happy Elements as one of the adopters
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#3529 fix: typo
  README.md
Labels: lgtm, needs-ok-to-test, approved

#3518 Ⅰ: This pr is to update license in pkg/ddc/goosefs/operations/local_test.go
  pkg/ddc/goosefs/operations/local_test.go
Labels: lgtm, needs-ok-to-test, approved

#3520 This pr is to update license in pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/transform.go
Labels: lgtm, needs-ok-to-test, approved

#3533 Update the concept diagram
  docs/en/core-concepts/introduction.md
  static/concepts/perspective_en.png
Labels: lgtm, approved

#3525 This pr is to add update apache license in "pkg/ddc/goosefs/create_volume.go"
  pkg/ddc/goosefs/create_volume.go
Labels: lgtm, needs-ok-to-test, approved

#3527 modify: change copyright year 2022 -> 2023
  pkg/ddc/goosefs/engine.go
Labels: lgtm, needs-ok-to-test, approved

#3531 Update apache license for pkg/ddc/efc/dataset_test.go
  pkg/ddc/efc/dataset_test.go
Labels: lgtm, needs-ok-to-test, approved

#3537 Fix JindoRuntime support volume mount
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/jindocache/CHANGELOG.md
  charts/jindocache/Chart.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/values.yaml
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/Chart.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  pkg/ddc/jindo/master_internal.go
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/master_internal.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_fuse_test.go
  pkg/ddc/jindocache/transform_test.go
  pkg/ddc/jindocache/types.go
  pkg/ddc/jindofsx/master_internal.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/transform_test.go
  pkg/ddc/jindofsx/types.go
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#3539 juicefs: make juicefsruntime.spec.fuse configurale
  pkg/ddc/juicefs/sync_runtime.go
  pkg/ddc/juicefs/utils.go
Labels: lgtm, approved

#3543 Build docker images for configurable juicefs runtime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3548 Fix upgrade job has dots issue, To #51060667
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
Labels: lgtm, approved

#3542 delete a blank line to normalize license
  pkg/ddc/alluxio/transform_init_users_test.go
Labels: lgtm, needs-ok-to-test, approved

#3532 This pr is to add Apache License for node_test.go
  pkg/utils/dataset/lifecycle/node_test.go
Labels: lgtm, needs-ok-to-test, approved

#3563 modify 2022 to 2023 in pkg/ddc/goosefs/transform_hadoop_config.go
  pkg/ddc/goosefs/transform_hadoop_config.go
Labels: lgtm, needs-ok-to-test, approved

#3564 Update the license in pkg/ddc/jindo/transform_test.go
  pkg/ddc/jindo/transform_test.go
Labels: lgtm, needs-ok-to-test, approved

#3549 Docs: automatic clean up data operation
  docs/en/TOC.md
  docs/en/samples/automatic_clean_up_data_operation.md
  docs/zh/TOC.md
  docs/zh/samples/automatic_clean_up_data_operation.md
Labels: needs-ok-to-test

#3565 add License
  pkg/webhook/plugins/fusesidecar/fuse_sidecar_test.go
Labels: lgtm, needs-ok-to-test, approved

#3555 Add the vineyard runtime CRD definitions.
  PROJECT
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/vineyardruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_vineyardruntimes.yaml
  config/crd/patches/webhook_in_vineyardruntimes.yaml
  config/rbac/vineyardruntime_editor_role.yaml
  config/rbac/vineyardruntime_viewer_role.yaml
  config/samples/data_v1alpha1_vineyardruntime.yaml
Labels: lgtm, needs-ok-to-test, approved

#3569 task64, add license
  pkg/application/inject/fuse/mutator/mutator_unprivileged.go
Labels: lgtm, needs-ok-to-test, approved

#3573 【task58】：update the license of pkg/utils/runtimes/options/init.go
  pkg/utils/runtimes/options/init.go
Labels: lgtm, needs-ok-to-test, approved

#3571 feat: data operations support resources
  api/v1alpha1/dataload_types.go
  api/v1alpha1/datamigrate_types.go
  api/v1alpha1/dataprocess_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-dataloader/alluxio/templates/cronjob.yaml
  charts/fluid-dataloader/alluxio/templates/job.yaml
  charts/fluid-dataloader/alluxio/values.yaml
  charts/fluid-dataloader/jindocache/templates/cronjob.yaml
  charts/fluid-dataloader/jindocache/templates/job.yaml
  charts/fluid-dataloader/jindocache/values.yaml
  charts/fluid-dataloader/jindofsx/templates/cronjob.yaml
  charts/fluid-dataloader/jindofsx/templates/job.yaml
  charts/fluid-dataloader/jindofsx/values.yaml
  charts/fluid-dataloader/juicefs/templates/cronjob.yaml
  charts/fluid-dataloader/juicefs/templates/job.yaml
  charts/fluid-dataloader/juicefs/values.yaml
  charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
  charts/fluid-datamigrate/juicefs/templates/job.yaml
  charts/fluid-datamigrate/juicefs/values.yaml
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid-dataprocess/common/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/dataload/value.go
  pkg/datamigrate/value.go
  pkg/dataprocess/value.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/goosefs/transform_hadoop_config.go
  pkg/ddc/jindocache/load_data.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/webhook/plugins/fusesidecar/fuse_sidecar_test.go
  test/prow/testcases/common/cron_dataload.py
Labels: lgtm, approved

#3570 update the license of pkg/ddc/juicefs/transform_volume.go
  pkg/ddc/juicefs/transform_volume.go
Labels: lgtm, needs-ok-to-test, approved

#3535 change pkg/ddc/jindofsx/load_data.go license
  pkg/ddc/jindofsx/load_data.go
Labels: needs-ok-to-test

#3584 Optimize documents and synchronize English versions
  docs/en/userguide/faq.md
  docs/zh/userguide/faq.md
Labels: lgtm, needs-ok-to-test, approved
