Repository fluid-cloudnative/fluid, pull requests merged in 2023-10, with the labels that each got.

#3469 Remove unused CLIENT_STORAGE_RPC_HOST env from jindo engines
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/fuse/daemonset.yaml
Labels: lgtm, approved

#3440 Feature: support symlink for NodePublish
  charts/fluid/fluid/templates/csi/daemonset.yaml
  charts/fluid/fluid/values.yaml
  pkg/common/label.go
  pkg/common/volume.go
  pkg/csi/plugins/nodeserver.go
  pkg/csi/recover/register.go
  pkg/utils/dataset/volume/create.go
  pkg/utils/symlink.go
  test/prow/fluid/fluidapi.py
  test/prow/testcases/common/csi_nodepublish_symlink.py
Labels: lgtm, approved, ok-to-test

#3470 Build docker images for symlink support
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3471 Refactor ttl
  pkg/controllers/operation_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
  pkg/controllers/v1alpha1/dataprocess/dataprocess_controller.go
  pkg/dataoperation/interface.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/base/engine.go
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/operation.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/efc/operate.go
  pkg/ddc/goosefs/operate.go
  pkg/ddc/jindo/operate.go
  pkg/ddc/jindocache/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/operate.go
  pkg/ddc/thin/referencedataset/engine.go
  pkg/utils/dataoperation.go
  pkg/utils/dataoperation_test.go
Labels: lgtm, approved

#3476 Update ADOPTERS.md
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#3474 bugfix: fix secret volume mounts for jindofsx and jindocache engine
  charts/jindocache/CHANGELOG.md
  charts/jindocache/Chart.yaml
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/templates/worker/statefulset.yaml
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/Chart.yaml
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
Labels: lgtm, approved

#3478 Build docker images for jindofuse bug fix
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3481 Enhanced the install user guide document
  docs/en/userguide/install.md
  docs/zh/userguide/install.md
Labels: lgtm, needs-ok-to-test, approved

#3461 Support tiered locality scheduling for app pod
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_efcruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  charts/fluid/fluid/templates/webhook/tiered-conf.yaml
  charts/fluid/fluid/values.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_efcruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/common/constants.go
  pkg/ddc/alluxio/status.go
  pkg/ddc/goosefs/status.go
  pkg/ddc/jindo/status.go
  pkg/ddc/jindocache/status.go
  pkg/ddc/jindofsx/status.go
  pkg/ddc/juicefs/status.go
  pkg/ddc/thin/status.go
  pkg/utils/kubeclient/pod.go
  pkg/utils/kubeclient/pod_test.go
  pkg/utils/webhook.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache_test.go
  pkg/webhook/plugins/nodeaffinitywithcache/tiered_locaity.go
  pkg/webhook/plugins/plugins_test.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
Labels: lgtm, approved

#3484 Build docker images for tiered scheduling
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3488 Enable alluxio web ui
  pkg/ddc/alluxio/transform_optimization.go
Labels: lgtm, needs-ok-to-test, approved

#3477 refactor: refactor fuse sidecar injection with mutator (phase 1)
  pkg/application/inject/fuse/container.go
  pkg/application/inject/fuse/injector.go
  pkg/application/inject/fuse/mutating_context.go
  pkg/application/inject/fuse/mutator.go
  pkg/application/inject/fuse/volume.go
  pkg/application/inject/fuse/volume_mount.go
  pkg/common/types.go
  pkg/ddc/base/runtime.go
  pkg/ddc/base/runtime_helper.go
Labels: lgtm, approved

#3479 Refactor ttl phase 2
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/controllers/v1alpha1/dataprocess/implement.go
  pkg/dataoperation/interface.go
  pkg/dataoperation/mock.go
  pkg/ddc/base/operation.go
  pkg/utils/dataoperation.go
  pkg/utils/dataoperation_test.go
Labels: lgtm, approved

#3489 add tiered locality sceduling docs and set the default tiered locality configuration
  charts/fluid/fluid/values.yaml
  docs/en/TOC.md
  docs/en/operation/pod_schedule_optimization.md
  docs/en/operation/tiered_locality_schedule.md
  docs/zh/TOC.md
  docs/zh/operation/pod_schedule_optimization.md
  docs/zh/operation/tiered_locality_schedule.md
  pkg/webhook/plugins/nodeaffinitywithcache/tiered_locaity.go
  pkg/webhook/plugins/nodeaffinitywithcache/tiered_locaity_test.go
Labels: lgtm, approved

#3492 refactor: refactor fuse sidecar mutator with pod-level info
  pkg/application/inject/fuse/injector.go
  pkg/application/inject/fuse/mount_point_script.go
  pkg/application/inject/fuse/mutator/mutator.go
  pkg/application/inject/fuse/mutator/mutator_default.go
  pkg/application/inject/fuse/mutator/mutator_unprivileged.go
Labels: lgtm, approved

#3491 enhancement: recover fuse according to multiple peer group options
  charts/fluid/fluid/templates/csi/daemonset.yaml
  pkg/utils/map.go
  pkg/utils/map_test.go
  pkg/utils/mountinfo/mountinfo.go
  pkg/utils/mountinfo/mountinfo_test.go
  pkg/utils/mountinfo/mountpoint.go
  pkg/utils/mountinfo/mountpoint_test.go
Labels: lgtm, approved

#3494 Build docker images for webhook refactoring
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3497 Fix helm upgrade issue due to no patch permission
  tools/crd-upgrade/upgrade-crds.sh
Labels: lgtm, approved

#3501 Build docker images for fixing helm upgrade
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3500 auto clean up crd-upgrade pod
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#3503 Build docker image for crd upgrader
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3507 Updated copyright
  pkg/ddc/jindo/health_check_test.go
Labels: lgtm, needs-ok-to-test, approved
