Repository fluid-cloudnative/fluid, pull requests merged in 2023-08, with the labels that each got.

#3367 feat: data process implementation
  api/v1alpha1/dataprocess_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-dataprocess/.helmignore
  charts/fluid-dataprocess/common/Chart.yaml
  charts/fluid-dataprocess/common/templates/_helpers.tpl
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid-dataprocess/common/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/common/constants.go
  pkg/controllers/operation_controller.go
  pkg/controllers/v1alpha1/dataprocess/implement.go
  pkg/controllers/v1alpha1/dataprocess/status_handler.go
  pkg/dataoperation/context.go
  pkg/dataprocess/constants.go
  pkg/dataprocess/generate_values.go
  pkg/dataprocess/generate_values_test.go
  pkg/dataprocess/processor_types.go
  pkg/dataprocess/processor_types_test.go
  pkg/dataprocess/value.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/alluxio/process_data.go
  pkg/ddc/alluxio/process_data_test.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/efc/data_process.go
  pkg/ddc/efc/data_process_test.go
  pkg/ddc/efc/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/jindofsx/process_data.go
  pkg/ddc/jindofsx/process_data_test.go
  pkg/ddc/juicefs/data_process.go
  pkg/ddc/juicefs/data_process_test.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/data_process.go
  pkg/ddc/thin/data_process_test.go
  pkg/ddc/thin/operate.go
  pkg/utils/dataprocess.go
Labels: lgtm, approved

#3376 add ut for status_handler
  pkg/controllers/v1alpha1/databackup/status_handler_test.go
  pkg/controllers/v1alpha1/dataload/status_handler_test.go
  pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
  pkg/controllers/v1alpha1/dataprocess/status_handler_test.go
Labels: lgtm, needs-ok-to-test, approved

#3380 del metadata sync && del duplicate metrics
  pkg/ddc/juicefs/cache.go
  pkg/ddc/juicefs/cache_test.go
  pkg/ddc/juicefs/metadata.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/juicefs/operations/base_test.go
Labels: lgtm, approved

#3375 enhancement: accurately calculate data operation's duration
  pkg/controllers/v1alpha1/databackup/status_handler.go
  pkg/controllers/v1alpha1/dataload/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/controllers/v1alpha1/dataprocess/status_handler.go
Labels: lgtm, needs-ok-to-test, approved

#3385 Build docker images for fixing controller's OOM
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3386 Support service account name for DataProcess
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid-dataprocess/common/values.yaml
  pkg/dataprocess/generate_values.go
  pkg/dataprocess/value.go
Labels: lgtm, approved

#3388 Remove stale docs
  docs-new/README.md
  docs-new/README_zh.md
  docs-new/zh/TOC.md
  docs-new/zh/concepts/overview.md
  docs-new/zh/dev/api_doc.md
  docs-new/zh/dev/how_to_develop.md
  docs-new/zh/dev/images/dataset_lifecycle.png
  docs-new/zh/dev/images/runtime_lifecycle.png
  docs-new/zh/dev/multiple-client-support.md
  docs-new/zh/dev/runtime_dev_guide.md
  docs-new/zh/dev/use_go_create_resource.md
  docs-new/zh/installation/get_started.md
  docs-new/zh/installation/installation.md
  docs-new/zh/installation/upgrade.md
  docs-new/zh/operation/collect_log.md
  docs-new/zh/operation/debug-fuse.md
  docs-new/zh/operation/faq.md
  docs-new/zh/runtime_alluxio/README.md
  docs-new/zh/runtime_alluxio/operation/README.md
  docs-new/zh/runtime_alluxio/operation/faq.md
  docs-new/zh/runtime_alluxio/operation/images/dataset_auto_scaling.png
  docs-new/zh/runtime_alluxio/operation/images/grafana-monitor.jpg
  docs-new/zh/runtime_alluxio/operation/images/grafana-prometheus-setting.jpg
  docs-new/zh/runtime_alluxio/operation/monitoring.md
  docs-new/zh/runtime_alluxio/operation/profiling.md
  docs-new/zh/runtime_alluxio/task/README.md
  docs-new/zh/runtime_alluxio/task/configuration/tieredstore_config.md
  docs-new/zh/runtime_alluxio/task/databackup/data_backup_and_restore_metadata.md
  docs-new/zh/runtime_alluxio/task/dataload/data_warmup.md
  docs-new/zh/runtime_alluxio/task/dataset_scaling/dataset_auto_scaling.md
  docs-new/zh/runtime_alluxio/task/dataset_scaling/dataset_cron_scaling.md
  docs-new/zh/runtime_alluxio/task/dataset_scaling/dataset_scaling.md
  docs-new/zh/runtime_alluxio/task/dataset_schedule/data_co_locality.md
  docs-new/zh/runtime_alluxio/task/dataset_schedule/data_toleration.md
  docs-new/zh/runtime_alluxio/task/dataset_schedule/multi_dataset_same_node_accessing.md
  docs-new/zh/runtime_alluxio/task/dataset_schedule/pod_schedule_global.md
  docs-new/zh/runtime_alluxio/task/dataset_usage/accelerate_data_accessing.md
  docs-new/zh/runtime_alluxio/task/dataset_usage/accelerate_data_accessing_by_hdfs.md
  docs-new/zh/runtime_alluxio/task/dataset_usage/api_proxy.md
  docs-new/zh/runtime_alluxio/task/examples/machinelearning.md
  docs-new/zh/runtime_alluxio/task/high_avaliable/fuse_recover.md
  docs-new/zh/runtime_alluxio/task/high_avaliable/master_high_availiable.md
  docs-new/zh/runtime_alluxio/task/security/nonroot_access.md
  docs-new/zh/runtime_alluxio/task/security/use_encryptoptions.md
  docs-new/zh/runtime_alluxio/task/serverless/application_controller.md
  docs-new/zh/runtime_alluxio/task/serverless/knative.md
  docs-new/zh/runtime_alluxio/task/under_storage/accelerate_pvc.md
  docs-new/zh/runtime_alluxio/task/under_storage/gcs_configuration.md
  docs-new/zh/runtime_alluxio/task/under_storage/hdfs_configuration.md
  docs-new/zh/runtime_alluxio/task/under_storage/hostpath.md
  docs-new/zh/runtime_alluxio/task/under_storage/s3_configuration.md
Labels: lgtm, approved

#3384 feature: support dataflow
  api/v1alpha1/common.go
  api/v1alpha1/databackup_types.go
  api/v1alpha1/dataload_types.go
  api/v1alpha1/datamigrate_types.go
  api/v1alpha1/dataprocess_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  cmd/dataset/app/dataset.go
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/common/constants.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/dataflow/dataflow_controller.go
  pkg/controllers/v1alpha1/dataflow/operations.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/controllers/v1alpha1/dataprocess/implement.go
  pkg/dataoperation/context.go
  pkg/dataoperation/interface.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/base/operation.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/efc/operate.go
  pkg/ddc/goosefs/operate.go
  pkg/ddc/jindo/operate.go
  pkg/ddc/jindocache/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/operate.go
  pkg/utils/dataoperation.go
Labels: lgtm, approved

#3393 bugfix: clean up orphaned thinruntime resources
  charts/thin/templates/config/runtime.yaml
  charts/thin/templates/fuseconfig/fuseconfig.yaml
  pkg/ddc/thin/shutdown.go
  pkg/ddc/thin/shutdown_test.go
Labels: lgtm, approved

#3387 [JuiceFS] split ce&ee image
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/values.yaml
  pkg/common/juicefs.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/juicefs/transform_test.go
  pkg/ddc/juicefs/utils.go
  pkg/ddc/juicefs/utils_test.go
Labels: lgtm, approved

#3394 support auth config for juicefs & add no-update for juicefs mount
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/juicefs/transform_test.go
Labels: lgtm, approved

#3395 Build docker images for fixing juicefs startup issue
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3398 docfix: fix thinruntime example for sidecar mode
  docs/zh/samples/thinruntime.md
Labels: lgtm, approved

#3397 add ownerReference in resource & remove residual resource
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/role/rbac.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
  cmd/juicefs/app/juicefs.go
  pkg/controllers/manager.go
  pkg/ddc/juicefs/master_internal_test.go
  pkg/ddc/juicefs/shutdown.go
  pkg/ddc/juicefs/shutdown_test.go
  pkg/ddc/juicefs/utils.go
  pkg/utils/kubeclient/pod_test.go
  pkg/utils/kubeclient/rbac.go
  pkg/utils/kubeclient/rbac_test.go
Labels: lgtm, approved

#3402 docs: build fluid compnent
  docs/en/dev/how_to_develop.md
  docs/zh/dev/how_to_develop.md
Labels: lgtm, needs-ok-to-test, approved

#3403 Bugfix: remove umountDuplicate and add warning event
  charts/fluid/fluid/templates/csi/daemonset.yaml
  charts/fluid/fluid/values.yaml
  pkg/csi/recover/recover.go
  pkg/csi/recover/recover_test.go
  pkg/utils/env.go
  pkg/utils/env_test.go
  pkg/utils/time_tracker.go
  pkg/webhook/cache/runtime_info_cache.go
  pkg/webhook/scheduler/mutating/schedule_pod_handler.go
Labels: lgtm, needs-ok-to-test, approved

#3407 bugfix: fix failure when auto-upgrading Fluid CRDs
  docker/Dockerfile.crds
Labels: lgtm, approved

#3412 add fuse option doc
  docs/zh/samples/juicefs/juicefs_cache_dir.md
Labels: lgtm, approved

#3414 fix fuse memory limit when cache-size set in fuse.options
  pkg/ddc/juicefs/transform_resources.go
Labels: lgtm, approved

#3411 Update debug-fuse doc
  docs/zh/troubleshooting/debug-fuse.md
Labels: lgtm, approved

#3416 Docker build for fixing juice fuse option
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3378 support alluxioruntime with no secret and generate idempotent mount scripts
  charts/alluxio/templates/config/alluxio-mount-conf.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/values.yaml
  pkg/common/constants.go
  pkg/ddc/alluxio/const.go
  pkg/ddc/alluxio/master_internal.go
  pkg/ddc/alluxio/operations/base.go
  pkg/ddc/alluxio/operations/base_test.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_test.go
  pkg/ddc/alluxio/transform_volumes.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/ufs.go
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/goosefs/ufs_internal.go
  pkg/utils/dataset.go
  pkg/utils/kubeclient/configmap.go
  pkg/utils/ufs_path_builder.go
  pkg/utils/ufs_path_builder_test.go
Labels: lgtm, approved

#3419 Build docker images for refactoring alluxio
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3423 feat: allow users to skip inject post start hook when using Fuse Sidecar
  pkg/application/inject/fuse/injector.go
  pkg/common/constants.go
  pkg/common/types.go
  pkg/ddc/base/runtime_helper.go
  pkg/utils/annotations.go
  pkg/utils/annotations_test.go
Labels: lgtm, approved

#3390 feature: support pod metadata for DataProcess and simplify script processor's API
  api/v1alpha1/dataprocess_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-dataprocess/common/templates/configmap.yaml
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid-dataprocess/common/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/dataprocess/generate_values.go
  pkg/dataprocess/generate_values_test.go
  pkg/dataprocess/processor_types.go
  pkg/dataprocess/value.go
Labels: lgtm, approved

#3426 feat: support dataprocess without mounting dataset
  pkg/dataprocess/generate_values.go
  pkg/dataprocess/generate_values_test.go
Labels: lgtm, approved

#3421 Make dataset options still effective for juicefsRuntime
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
Labels: approved

#3425 alluxio using post start instead of startup probe when k8s version is less than 1.18
  charts/alluxio/templates/master/statefulset.yaml
Labels: lgtm, approved

#3428 enhancement: rename data operation's `spec.runAfter.operationKind` for extensibility
  api/v1alpha1/common.go
  api/v1alpha1/openapi_generated.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/controllers/v1alpha1/dataflow/operations.go
  pkg/utils/dataoperation.go
Labels: lgtm, approved

#3422 support worker of juicefs can be update by runtime
  pkg/common/constants.go
  pkg/ddc/juicefs/sync_runtime.go
  pkg/ddc/juicefs/sync_runtime_test.go
  pkg/ddc/juicefs/utils.go
  pkg/ddc/juicefs/utils_test.go
Labels: lgtm, approved

#3431 Build docker images for juicefsruntime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved
