Repository fluid-cloudnative/fluid, pull requests merged in 2023-06, with the labels that each got.

#3257 fix dataoperation when nil
  api/v1alpha1/dataset_types.go
  api/v1alpha1/dataset_types_test.go
Labels: lgtm, approved

#3259 Build docker image for data operation refactoring
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3261 fix dataoperation when nil
  api/v1alpha1/dataset_types.go
Labels: lgtm, approved

#3262 Fix default Alluxio writetype config
  pkg/ddc/alluxio/transform_optimization.go
Labels: lgtm, needs-ok-to-test, approved

#3224 add cron for data migrate
  api/v1alpha1/datamigrate_types.go
  api/v1alpha1/openapi_generated.go
  charts/fluid-datamigrate/juicefs/CHANGELOG.md
  charts/fluid-datamigrate/juicefs/Chart.yaml
  charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
  charts/fluid-datamigrate/juicefs/templates/job.yaml
  charts/fluid-datamigrate/juicefs/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  pkg/common/label.go
  pkg/controllers/operation_controller.go
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/databackup/status_handler.go
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/dataload/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/datamigrate/value.go
  pkg/dataoperation/interface.go
  pkg/ddc/base/operation.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/utils/datamigrate.go
Labels: lgtm, approved

#3266 Build docker images for cron data migrate
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3270 Update runtime info in dataset's status during binding
  pkg/ddc/alluxio/dataset.go
  pkg/ddc/alluxio/dataset_test.go
  pkg/ddc/efc/dataset.go
  pkg/ddc/efc/dataset_test.go
  pkg/ddc/jindofsx/dataset.go
  pkg/ddc/jindofsx/dataset_test.go
  pkg/ddc/juicefs/dataset.go
  pkg/ddc/juicefs/dataset_test.go
  pkg/ddc/thin/dataset.go
  pkg/ddc/thin/dataset_test.go
Labels: lgtm, approved

#3271 Print error message when failing to helm install
  pkg/utils/helm/utils.go
Labels: lgtm, approved

#3268 add labelSelector of cronjob in datamigrate controller
  charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
  cmd/dataset/app/dataset.go
  pkg/common/constants.go
Labels: lgtm, approved

#3273 Build docker image for optimzing runtimeinfo
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3274 fix jindoruntime support pvc subpath
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/transform_test.go
  pkg/ddc/jindofsx/types.go
Labels: lgtm, approved

#3275 Feat: add crdUpgrade enabled flag
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#3278 Build docker image for fixing jindoruntime subpath for pvc
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3281 fix default master journal type setting
  pkg/ddc/alluxio/transform_optimization.go
Labels: lgtm, needs-ok-to-test, approved

#3285 bugfix: fix cron DataMigrate for Kubernetes 1.20
  Makefile
  charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/utils/compatibility/batch.go
  pkg/utils/datamigrate.go
  pkg/utils/kubeclient/cronjob.go
  pkg/utils/kubeclient/cronjob_test.go
  pkg/utils/kubeclient/pod_test.go
  pkg/utils/testutil/unit_test_env.go
Labels: lgtm, approved

#3287 bugfix: fix csi plugin loop mount bug
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/templates/csi/daemonset.yaml
Labels: lgtm, approved

#3289 Build docker image for fixing cron data migrate
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3290 bugfix: fix csi plugin loop mount bug (#3287)
  charts/fluid/fluid/CHANGELOG.md
  charts/fluid/fluid/templates/csi/daemonset.yaml
Labels: lgtm, approved

#3294 Build docker image for release 0.9.1
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3288 fix operationRef dup
  api/v1alpha1/dataset_types.go
  api/v1alpha1/dataset_types_test.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/juicefs/dataset.go
  test/prow/testcases/juicefs/juicefs_minio.py
Labels: lgtm, approved

#3284 check path existence and lock in NodeUnpublishVolume
  pkg/csi/plugins/driver.go
  pkg/csi/plugins/nodeserver.go
  pkg/utils/volume_lock.go
Labels: lgtm, approved, ok-to-test

#3297 fix keyerror in e2e test
  test/prow/testcases/juicefs/juicefs_minio.py
Labels: lgtm, approved

#3299 Build docker image for making csi more robust
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3298 add ut for volume_lock
  pkg/utils/volume_lock.go
  pkg/utils/volume_lock_test.go
Labels: lgtm, needs-ok-to-test, approved

#2602 test: add e2e testcase 11, scale alluxio runtime
  test/prow/scale_runtime.py
Labels: lgtm, needs-ok-to-test, approved

#3272 Use configmap helm driver instead of secrets
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/efc/rbac.yaml
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/fluid/fluid/templates/role/thin/rbac.yaml
  cmd/alluxio/app/alluxio.go
  cmd/dataset/app/dataset.go
  cmd/efc/app/efc.go
  cmd/jindo/app/jindo.go
  cmd/juicefs/app/juicefs.go
  cmd/thin/app/thin.go
  pkg/controllers/manager.go
Labels: lgtm, approved

#3305 del secret get of juicefs runtime clusterrole
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/utils.go
  pkg/ddc/juicefs/utils_test.go
Labels: lgtm, approved

#3306 Build docker images for removing rbac of listing secret
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3291 fix default master journal type setting (#3281)
  pkg/ddc/alluxio/transform_optimization.go
Labels: lgtm, approved

#3311 feat: add megvii adopters
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#3310 Build docker images for removing secrets dependency of juicefs
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3300 bugfix: reconcile thinruntime failed when dataset is deleted
  pkg/controllers/runtime_controller.go
  pkg/ddc/base/dataset.go
  pkg/ddc/base/dataset_test.go
  pkg/ddc/thin/engine.go
  pkg/ddc/thin/engine_test.go
  pkg/ddc/thin/referencedataset/cm.go
  pkg/ddc/thin/referencedataset/engine.go
  pkg/ddc/thin/referencedataset/engine_test.go
  pkg/ddc/thin/referencedataset/runtime.go
  pkg/ddc/thin/referencedataset/runtime_test.go
  pkg/ddc/thin/referencedataset/sync.go
  pkg/ddc/thin/referencedataset/volume.go
Labels: lgtm, needs-ok-to-test, approved

#3314 fix fuse ImagePullPolicy
  pkg/ddc/alluxio/transform_fuse.go
  pkg/ddc/goosefs/transform_fuse.go
Labels: lgtm, needs-ok-to-test, approved

#3313 feature: add option to allow users to choose helm driver for Fluid controllers
  charts/fluid/fluid/templates/_helpers.tpl
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  charts/fluid/fluid/templates/role/alluxio/rbac.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/efc/rbac.yaml
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/fluid/fluid/templates/role/thin/rbac.yaml
  charts/fluid/fluid/values.yaml
  cmd/alluxio/app/alluxio.go
  cmd/dataset/app/dataset.go
  cmd/efc/app/efc.go
  cmd/jindo/app/jindo.go
  cmd/juicefs/app/juicefs.go
  cmd/thin/app/thin.go
  pkg/controllers/manager.go
Labels: lgtm, approved

#3319 docs: apply fluid to production
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved
