Repository fluid-cloudnative/fluid, pull requests merged in 2024-08, with the labels that each got.

#4243 add dataflow affinity doc
  docs/en/TOC.md
  docs/en/samples/dataflow_affinity.md
  docs/zh/TOC.md
  docs/zh/samples/dataflow_affinity.md
Labels: lgtm, approved

#4244 Build docker images for upgrading K8s to 1.29
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4245 enhance: validate dataset mounts before reconiling thinruntimes
  pkg/common/constants.go
  pkg/controllers/runtime_controller.go
  pkg/ddc/alluxio/validate.go
  pkg/ddc/base/engine.go
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/template_engine.go
  pkg/ddc/efc/validate.go
  pkg/ddc/goosefs/validate.go
  pkg/ddc/jindo/validate.go
  pkg/ddc/jindocache/validate.go
  pkg/ddc/jindofsx/validate.go
  pkg/ddc/juicefs/validate.go
  pkg/ddc/thin/referencedataset/validate.go
  pkg/ddc/thin/transform_config.go
  pkg/ddc/thin/transform_fuse.go
  pkg/ddc/thin/type.go
  pkg/ddc/thin/validate.go
  pkg/ddc/vineyard/validate.go
Labels: lgtm, approved

#4242 feat: support hierarchical imagePullSecrets configuration in AlluxioRuntime
  api/v1alpha1/alluxioruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
  charts/alluxio/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  pkg/ddc/alluxio/master_internal_test.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/transform_fuse.go
  pkg/ddc/alluxio/transform_test.go
  pkg/ddc/alluxio/types.go
  pkg/ddc/alluxio/utils.go
  pkg/ddc/alluxio/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#4251 update adopters
  ADOPTERS.md
Labels: lgtm, needs-ok-to-test, approved

#4247 jindo: fix master and worker ports of jindo runtime
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindofsx/transform.go
Labels: lgtm, needs-ok-to-test, approved

#4253 bugfix: fix options affecting sharedOptions in other mounts
  pkg/ddc/thin/ufs_internal.go
  pkg/utils/map.go
  pkg/utils/map_test.go
Labels: lgtm, approved

#4254 bugfix: Support data process operation type for JindoCache engine
  pkg/ddc/jindocache/operate.go
  pkg/ddc/jindocache/process_data.go
Labels: lgtm, approved

#4246 Build docker images for adding validation for runtime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4258 bugfix: support setting resources for dataprocess
  pkg/dataprocess/processor_types.go
Labels: lgtm, approved

#4260 Build docker images for fixing resources of data process
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4262 Add helm version option in Makefile
  Makefile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
Labels: lgtm, needs-ok-to-test, approved

#4264 Fix circleci issue
  .circleci/config.yml
Labels: lgtm, approved

#4261 add customized label affinity demo for data flow
  docs/en/samples/dataflow_affinity.md
  docs/zh/samples/dataflow_affinity.md
Labels: lgtm, approved

#4267 Make JindoRuntime sync Ufs total size with a longer timeout
  pkg/ddc/jindocache/operations/base.go
  pkg/ddc/jindofsx/operations/base.go
  pkg/utils/kubeclient/exec.go
Labels: lgtm, approved

#4268 Build docker imagews for fixing sync ufs issue
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4274 optimize mount logic && fix calculating ufs total size for JindoRuntime
  cmd/csi/app/csi.go
  pkg/common/alluxio.go
  pkg/common/constants.go
  pkg/common/ufs_path.go
  pkg/ddc/alluxio/transform.go
  pkg/ddc/alluxio/ufs_internal.go
  pkg/ddc/goosefs/ufs_internal.go
  pkg/ddc/jindocache/operations/base.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/ufs_internal.go
  pkg/ddc/jindocache/utils.go
  pkg/ddc/jindofsx/operations/base.go
  pkg/ddc/jindofsx/ufs_internal.go
  pkg/ddc/jindofsx/utils.go
  pkg/utils/dataset.go
  pkg/utils/pprof.go
  pkg/utils/ufs_path_builder.go
  pkg/utils/ufs_path_builder_test.go
Labels: lgtm, approved

#4278 Build docker images for fix calculating ufs total size
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4270 refactor: kubeclient exec utils package
  pkg/common/file_utils_exec.go
  pkg/ddc/alluxio/hcfs_test.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/alluxio/operations/base.go
  pkg/ddc/alluxio/operations/base_test.go
  pkg/ddc/alluxio/operations/conf_test.go
  pkg/ddc/alluxio/operations/local.go
  pkg/ddc/alluxio/operations/local_test.go
  pkg/ddc/alluxio/ufs_test.go
  pkg/ddc/alluxio/utils_test.go
  pkg/ddc/efc/operations/base.go
  pkg/ddc/efc/operations/base_test.go
  pkg/ddc/jindocache/operations/base.go
  pkg/ddc/jindocache/operations/base_test.go
  pkg/ddc/jindocache/operations/cached.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/juicefs/operations/base_test.go
  pkg/ddc/juicefs/ufs_test.go
  pkg/ddc/thin/operations/base.go
  pkg/ddc/thin/operations/base_test.go
  pkg/ddc/thin/ufs_test.go
  pkg/utils/kubeclient/exec.go
Labels: lgtm, approved

#4271 Refactor label keys in RuntimeInfo
  pkg/ddc/base/label.go
  pkg/ddc/base/label_test.go
  pkg/utils/label.go
Labels: lgtm, needs-ok-to-test, approved

#4280 Build docker images for refecator exec
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4281 disable metadata auto-sync for ThinRuntime by default
  api/v1alpha1/common.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/ddc/jindocache/cache_test.go
  pkg/ddc/thin/metadata.go
  pkg/ddc/thin/metadata_test.go
Labels: lgtm, approved

#4283 enhance: add timeout for kind-e2e github actions tests
  test/gha-e2e/alluxio/test.sh
  test/gha-e2e/jindo/test.sh
  test/gha-e2e/juicefs/test.sh
Labels: lgtm, approved

#4265 Bind all reconcile loops with limited context.Context
  pkg/controllers/runtime_controller.go
Labels: lgtm, needs-ok-to-test, approved

#4285 feat: add mounted dataset info to mutated app pods
  charts/fluid/fluid/values.yaml
  pkg/common/label.go
  pkg/ddc/base/label.go
  pkg/webhook/plugins/datasetusageinjector/dataset_usage_injector.go
  pkg/webhook/plugins/datasetusageinjector/dataset_usage_injector_test.go
  pkg/webhook/plugins/plugins_impl.go
Labels: approved

#4290 Build docker images for adding info of dataset in use
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4292 clean-up: remove unused functions
  pkg/ddc/jindocache/worker.go
  pkg/ddc/jindocache/worker_test.go
  pkg/ddc/jindofsx/worker.go
  pkg/ddc/jindofsx/worker_test.go
Labels: lgtm, needs-ok-to-test, approved

#4277 use annotation for exposed affinity for dataflow
  docs/en/samples/dataflow_affinity.md
  docs/zh/samples/dataflow_affinity.md
  pkg/common/label.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller_test.go
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
  pkg/dataflow/helper.go
  pkg/dataflow/helper_test.go
  pkg/dataprocess/generate_values.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/jindocache/load_data.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/utils/affinity.go
Labels: lgtm, approved

#4248 remove redundant update for performance
  pkg/ctrl/affinity.go
  pkg/ctrl/affinity_test.go
Labels: lgtm, needs-ok-to-test, approved

#4293 cleanup: Remove unnecessary comment
  pkg/ddc/alluxio/transform.go
  pkg/ddc/efc/transform.go
  pkg/ddc/goosefs/transform.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/juicefs/transform.go
  pkg/ddc/thin/transform.go
  pkg/ddc/vineyard/transform.go
Labels: lgtm, needs-ok-to-test, approved

#4299 Chore: Fixed docker build command in Makefile
  Makefile
Labels: lgtm, needs-ok-to-test, approved

#4302 add fuse properties with default xengine
  pkg/ddc/jindocache/transform.go
Labels: lgtm, approved

#4303 Build docker images for releasing v1.0.2
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved
