Repository fluid-cloudnative/fluid, pull requests merged in 2024-10, with the labels that each got.

#4335 fix: fix slice init length
  pkg/webhook/plugins/mountpropagationinjector/mount_propagation_injector.go
Labels: lgtm, needs-ok-to-test, approved

#4334 Refactor Makefile: Add .PHONY declarations
  Makefile
Labels: lgtm, approved

#4324 support dataflow affinity using any preceding data operations
  api/v1alpha1/common.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  docs/en/samples/dataflow_affinity.md
  docs/zh/samples/dataflow_affinity.md
  pkg/common/label.go
  pkg/controllers/v1alpha1/dataflow/operations.go
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
  pkg/utils/dataoperation.go
Labels: lgtm, approved

#4339 bugfix: avoid setting "storage.data-dirs.capacity" when using MEM as tieredstore's medium type
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_worker_test.go
Labels: lgtm, approved

#4331 feat: enable client-side metrics scraping for JindoCache engine
  api/v1alpha1/common.go
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/jindocache/templates/fuse/daemonset.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  pkg/application/inject/fuse/injector.go
  pkg/application/inject/fuse/injector_test.go
  pkg/application/inject/fuse/mutator/mutator_default.go
  pkg/application/inject/fuse/mutator/mutator_unprivileged.go
  pkg/common/label.go
  pkg/ddc/base/runtime.go
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/sync_runtime.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_test.go
  pkg/ddc/jindocache/types.go
  pkg/utils/map.go
  pkg/utils/map_test.go
Labels: lgtm, approved

#4340 Build docker image for supporting dataflow affinity
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4342 Make dataflow affinity's annotations consistent with others
  docs/zh/samples/dataflow_affinity.md
  pkg/common/label.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller_test.go
  pkg/dataflow/helper.go
  pkg/dataflow/helper_test.go
Labels: lgtm, approved

#4343 Revert PR #4339
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_worker_test.go
Labels: lgtm, approved

#4344 bugfix: add startup probe to gha-e2e minio setup
  test/gha-e2e/jindo/minio.yaml
Labels: lgtm, approved

#4348 feat: support imagePullSecrets in thinRuntime & thinRuntimeProfile
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/thinruntime_types.go
  api/v1alpha1/thinruntimeprofile_types.go
  charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  charts/thin/templates/fuse/daemonset.yaml
  charts/thin/templates/worker/statefuleset.yaml
  config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/ddc/thin/transform.go
  pkg/ddc/thin/transform_fuse.go
  pkg/ddc/thin/type.go
Labels: lgtm, approved

#4347 Fix: fix some typo and log fmt error
  charts/fluid-dataloader/jindocache/templates/configmap.yaml
  pkg/controllers/deploy/runtime_controllers.go
  pkg/controllers/deploy/runtime_controllers_test.go
  pkg/controllers/runtime_controller.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
  pkg/csi/plugins/controller.go
  pkg/csi/plugins/nodeserver.go
  pkg/csi/recover/recover.go
  pkg/csi/updatedbconf/register.go
  pkg/csi/updatedbconf/updatedbconf.go
  pkg/ctrl/replicas.go
  pkg/ctrl/watch/pod.go
  pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/deprecated_label.go
  pkg/ddc/alluxio/master.go
  pkg/ddc/alluxio/master_internal.go
  pkg/ddc/alluxio/metadata.go
  pkg/ddc/alluxio/node.go
  pkg/ddc/alluxio/report.go
  pkg/ddc/alluxio/report_test.go
  pkg/ddc/alluxio/runtime_info.go
  pkg/ddc/alluxio/shutdown.go
  pkg/ddc/alluxio/transform_fuse.go
  pkg/ddc/base/dataset.go
  pkg/ddc/efc/shutdown.go
  pkg/ddc/goosefs/report_test.go
  pkg/ddc/jindo/master_internal.go
  pkg/ddc/jindo/transform.go
  pkg/ddc/jindocache/master_internal.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/ufs.go
  pkg/ddc/jindocache/ufs_internal.go
  pkg/ddc/jindofsx/master_internal.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/ufs_internal.go
  pkg/ddc/juicefs/master_internal.go
  pkg/ddc/vineyard/report_test.go
  pkg/utils/dataset.go
  pkg/utils/helm/utils.go
Labels: lgtm, approved

#4349 feat: support imagePullSecrets in jindoRuntime
  api/v1alpha1/jindoruntime_types.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/templates/worker/statefulset.yaml
  charts/jindofs/templates/fuse/daemonset.yaml
  charts/jindofs/templates/master/statefulset.yaml
  charts/jindofs/templates/worker/statefulset.yaml
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  pkg/ddc/jindo/transform.go
  pkg/ddc/jindo/types.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/types.go
  pkg/ddc/jindofsx/transform.go
  pkg/ddc/jindofsx/types.go
Labels: lgtm, approved

#4346 feat: support mountMode configuration to skip checking mount ready
  pkg/common/label.go
  pkg/csi/plugins/nodeserver.go
  pkg/ddc/alluxio/runtime_info.go
  pkg/ddc/base/runtime.go
  pkg/ddc/efc/runtime_info.go
  pkg/ddc/goosefs/runtime_info.go
  pkg/ddc/jindo/runtime_info.go
  pkg/ddc/jindocache/runtime_info.go
  pkg/ddc/jindofsx/runtime_info.go
  pkg/ddc/juicefs/runtime_info.go
  pkg/ddc/thin/referencedataset/runtime.go
  pkg/ddc/thin/runtime_info.go
  pkg/ddc/vineyard/runtime_info.go
  pkg/utils/dataset/volume/create.go
Labels: lgtm, approved

#4351 Docker build for fixing the skipping check mount ready
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  pkg/controllers/runtime_controller.go
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
Labels: lgtm, approved

#4352 docs updated
  CONTRIBUTING.md
  README.md
  docs/en/dev/api_doc.md
  docs/en/dev/pprof.md
Labels: lgtm, needs-ok-to-test, approved

#4355 refactor: sync schedule info to cache nodes
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/ddc/alluxio/node.go
  pkg/ddc/alluxio/node_test.go
  pkg/ddc/base/runtime.go
  pkg/ddc/base/runtime_conventions.go
  pkg/ddc/efc/node.go
  pkg/ddc/goosefs/node.go
  pkg/ddc/goosefs/node_test.go
  pkg/ddc/jindo/node.go
  pkg/ddc/jindo/node_test.go
  pkg/ddc/jindocache/node.go
  pkg/ddc/jindocache/node_test.go
  pkg/ddc/jindofsx/node.go
  pkg/ddc/jindofsx/node_test.go
  pkg/ddc/juicefs/node.go
  pkg/ddc/juicefs/node_test.go
  pkg/ddc/thin/node.go
  pkg/ddc/thin/node_test.go
  pkg/ddc/vineyard/node.go
  pkg/ddc/vineyard/node_test.go
  pkg/utils/dataset/lifecycle/node.go
  pkg/utils/dataset/lifecycle/node_test.go
Labels: lgtm, approved

#4345 dataflow ensure the dependent operation was completed
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
Labels: lgtm, approved

#4359 [WIP] fix: fix the dataload with cronJob failure in jindoCacheRuntime
  charts/fluid-dataloader/jindocache/templates/cronjob.yaml
Labels: lgtm, do-not-merge/work-in-progress, approved

#4360 Fix: fix the invalid fmt of dataload cronJob helm template
  charts/alluxio/Chart.yaml
  charts/efc/Chart.yaml
  charts/fluid-databackup/alluxio/Chart.yaml
  charts/fluid-databackup/goosefs/Chart.yaml
  charts/fluid-dataloader/alluxio/CHANGELOG.md
  charts/fluid-dataloader/alluxio/Chart.yaml
  charts/fluid-dataloader/alluxio/templates/cronjob.yaml
  charts/fluid-dataloader/goosefs/CHANGELOG.md
  charts/fluid-dataloader/goosefs/Chart.yaml
  charts/fluid-dataloader/goosefs/templates/cronjob.yaml
  charts/fluid-dataloader/jindo/CHANGELOG.md
  charts/fluid-dataloader/jindo/Chart.yaml
  charts/fluid-dataloader/jindo/templates/cronjob.yaml
  charts/fluid-dataloader/jindocache/CHANGELOG.md
  charts/fluid-dataloader/jindocache/Chart.yaml
  charts/fluid-dataloader/jindocache/templates/cronjob.yaml
  charts/fluid-dataloader/jindofsx/CHANGELOG.md
  charts/fluid-dataloader/jindofsx/Chart.yaml
  charts/fluid-dataloader/jindofsx/templates/cronjob.yaml
  charts/fluid-dataloader/juicefs/CHANGELOG.md
  charts/fluid-dataloader/juicefs/Chart.yaml
  charts/fluid-dataloader/juicefs/templates/cronjob.yaml
  charts/fluid-datamigrate/juicefs/Chart.yaml
  charts/fluid-dataprocess/common/Chart.yaml
  charts/goosefs/Chart.yaml
  charts/jindocache/Chart.yaml
  charts/jindofs/Chart.yaml
  charts/jindofsx/Chart.yaml
  charts/juicefs/Chart.yaml
  charts/library/CHANGELOG.md
  charts/library/Chart.yaml
  charts/library/templates/_common_component_in_dataload_cronjob.tpl
  charts/thin/Chart.yaml
  charts/vineyard/Chart.yaml
Labels: lgtm, approved

#4362 Build docker images for fixing cron dataload with annotations
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4372 Revert to v1.0.3
  Makefile
  charts/fluid/fluid/Chart.yaml
Labels: lgtm, approved

#4373 fix some issues of helm chart
  charts/fluid-dataloader/juicefs/templates/cronjob.yaml
  charts/fluid/fluid/templates/_helpers.tpl
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
  charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
  charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
Labels: lgtm, approved

#4374 bugfix: fix NodeUnpublishVolume when checking corrupted mount points
  pkg/csi/plugins/nodeserver.go
  pkg/utils/mount.go
Labels: lgtm, approved

#4375 Docker build for fixing NodeUnpublishVolume when checking corrupted
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4378 Fix code scanning alert - Prefer COPY over ADD
  addons/cephfs/docker/Dockerfile
  addons/cubefs/v2.4/docker/Dockerfile
  addons/cubefs/v3.2/docker/Dockerfile
  addons/dynamic-mount/ossfs/docker/Dockerfile
  addons/glusterfs/docker/Dockerfile
  addons/nfs/docker/Dockerfile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
  samples/knative/docker/Dockerfile
Labels: lgtm, approved
