Repository fluid-cloudnative/fluid, pull requests merged in 2024-01, with the labels that each got.

#3677 fix disable compaction
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindofsx/transform.go
Labels: lgtm, approved

#3678 build docker images for disabling storage compaction
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3676 Create roadmap for 2024
  ROADMAP.md
Labels: approved

#3630 complete license
  pkg/utils/quantity.go
Labels: lgtm, needs-ok-to-test, approved

#3681 Build docker images for vineyard
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3684 change some fields from optional to required in CRD YAML
  api/v1alpha1/common.go
  api/v1alpha1/dataset_types.go
  api/v1alpha1/openapi_generated.go
  charts/fluid/fluid/crds/data.fluid.io_alluxioruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_datasets.yaml
  charts/fluid/fluid/crds/data.fluid.io_efcruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_goosefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_juicefsruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  config/crd/bases/data.fluid.io_alluxioruntimes.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_datasets.yaml
  config/crd/bases/data.fluid.io_efcruntimes.yaml
  config/crd/bases/data.fluid.io_goosefsruntimes.yaml
  config/crd/bases/data.fluid.io_jindoruntimes.yaml
  config/crd/bases/data.fluid.io_juicefsruntimes.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
Labels: lgtm, approved

#3689 Build docker images for fixing incorrect conversion of integer
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: approved

#3682 add fluid.io/fuse plugin parameter to schedule app pod to node with existed fuse pod
  charts/fluid/fluid/values.yaml
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache.go
  pkg/webhook/plugins/nodeaffinitywithcache/node_affinity_with_cache_test.go
Labels: lgtm, approved

#3691 fixes #3680-Update dingtalk group QR code image
  static/dingtalk.png
Labels: lgtm, approved

#3693 Docker build 240116
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  pkg/utils/quantity.go
Labels: lgtm, approved

#3597 pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go Copyright 2021 to 2023
  pkg/webhook/scheduler/mutating/schedule_pod_handler_test.go
Labels: lgtm, needs-ok-to-test, approved

#3578 增加/pkg/ddc/thin/status_test.go的license
  pkg/ddc/thin/status_test.go
Labels: lgtm, needs-ok-to-test, approved

#3583 update /pkg/ddc/base/engine.go license year 2022 -> 2023
  pkg/ddc/base/engine.go
Labels: lgtm, needs-ok-to-test, approved

#3591 Update the Copyright year in pkg/ddc/thin/ufs_internal.go
  pkg/ddc/thin/ufs_internal.go
Labels: lgtm, needs-ok-to-test, approved

#3592 Fix pkg/ddc/alluxio/worker_test.go: change Copyright 2022 to Copyright 2023
  pkg/ddc/alluxio/worker_test.go
Labels: lgtm, needs-ok-to-test, approved

#3598 Update license copyright date from 2022 to 2023
  pkg/ddc/efc/transform_resources.go
Labels: lgtm, needs-ok-to-test, approved

#3600 This pr is to update the year of the Apache License in pkg/ctrl/watch/pod.go
  pkg/ctrl/watch/pod.go
Labels: lgtm, needs-ok-to-test, approved

#3603 Update Apache license in `pkg/ddc/thin/metadata.go`
  pkg/ddc/thin/metadata.go
Labels: lgtm, needs-ok-to-test, approved

#3610 Changed the year from 2022 to 2023
  pkg/application/inject/fuse/container_test.go
Labels: lgtm, needs-ok-to-test, approved

#3611 change copyright 2022 to 2023
  pkg/ddc/efc/port_parser.go
Labels: lgtm, needs-ok-to-test, approved

#3667 modified 2022 to 2023
  pkg/utils/feature/feature_gate.go
Labels: lgtm, needs-ok-to-test, approved

#3612 fix copyright year from 2022 to 2023
  pkg/ddc/thin/ufs_test.go
Labels: lgtm, needs-ok-to-test, approved

#3577 pkg/ddc/thin/referencedataset/runtime.go years update to 2023
  pkg/ddc/thin/referencedataset/runtime.go
Labels: lgtm, needs-ok-to-test, approved

#3606 xxx
  pkg/ddc/base/log_test.go
Labels: lgtm, needs-ok-to-test, approved

#3618 update the pkg/ddc/juicefs/master_internal_test.go license copyright
  pkg/ddc/juicefs/master_internal_test.go
Labels: lgtm, needs-ok-to-test, approved

#3619 Updated copyright at pkg/ddc/thin/status.go
  pkg/ddc/thin/status.go
Labels: lgtm, needs-ok-to-test, approved

#3627 Update pkg/ddc/jindofsx/create_volume_test.go License
  pkg/ddc/jindofsx/create_volume_test.go
Labels: lgtm, needs-ok-to-test, approved

#3696 pass AccessModes to thinruntime fuse container
  pkg/ddc/thin/transform_config.go
  pkg/ddc/thin/transform_fuse_test.go
  pkg/ddc/thin/type.go
Labels: lgtm, approved

#3698 Remove unused method
  pkg/utils/kubectl/configmap.go
  pkg/utils/kubectl/configmap_test.go
Labels: lgtm, approved

#3692 Support pipe command
  pkg/ddc/alluxio/operations/base.go
  pkg/ddc/goosefs/hcfs_test.go
  pkg/ddc/goosefs/operations/base.go
  pkg/ddc/jindo/operations/base.go
  pkg/ddc/jindofsx/operations/base.go
  pkg/ddc/juicefs/data_load_test.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/thin/operations/base.go
  pkg/utils/helm/helm.go
  pkg/utils/helm/helm_test.go
  pkg/utils/shell_pipes.go
  pkg/utils/shell_pipes_test.go
Labels: lgtm, approved

#3686 Use utils.command to replace exec.command
  pkg/csi/plugins/nodeserver.go
  pkg/utils/exec.go
  pkg/utils/exec_test.go
  pkg/utils/helm/helm.go
  pkg/utils/helm/helm_test.go
  pkg/utils/helm/utils.go
  pkg/utils/helm/utils_test.go
  pkg/utils/home.go
  pkg/utils/kubectl/configmap.go
  pkg/utils/mount.go
  pkg/utils/mount_test.go
Labels: lgtm, approved

#3694 Integrate Fluid with Kubeflow Pipline
  integration/kubeflow/README.md
  integration/kubeflow/component-yaml/cleanup-dataset-and-alluxioruntime.yaml
  integration/kubeflow/component-yaml/cleanup-preheat-operation.yaml
  integration/kubeflow/component-yaml/create-alluxioruntime.yaml
  integration/kubeflow/component-yaml/create-s3-dataset.yaml
  integration/kubeflow/component-yaml/preheat-dataset.yaml
  integration/kubeflow/fluid_components.py
  integration/kubeflow/pipline-yaml/train-cnn-for-fashion-mnist-pipline.yaml
  integration/kubeflow/rbac.yaml
  integration/kubeflow/s3-secret.yaml
  integration/kubeflow/simple_cnn_sample.py
Labels: lgtm, approved

#3695 Add a regex to validate the resource before sending the http request in the vineyard Runtime
  pkg/ddc/vineyard/operations/base.go
  pkg/ddc/vineyard/operations/base_test.go
Labels: lgtm, needs-ok-to-test, approved

#3701 change enableServiceLinks from true to false
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/templates/worker/statefulset.yaml
  charts/jindofs/templates/fuse/daemonset.yaml
  charts/jindofs/templates/master/statefulset.yaml
  charts/jindofs/templates/worker/statefulset.yaml
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
Labels: lgtm, approved

#3700 Add a replicas field to the vineyard Runtime and delete the svc suffix in the vineyard helm chart.
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/vineyard/templates/_helpers.tpl
  charts/vineyard/templates/config/vineyard-rpc-conf.yaml
  charts/vineyard/templates/master/service.yaml
  charts/vineyard/templates/master/statefulset.yaml
  charts/vineyard/templates/worker/service.yaml
  charts/vineyard/templates/worker/statefulset.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  pkg/controllers/operation_controller.go
  pkg/ddc/vineyard/operations/base.go
  pkg/ddc/vineyard/operations/base_test.go
  pkg/ddc/vineyard/operator.go
  pkg/ddc/vineyard/process_data.go
  pkg/ddc/vineyard/process_data_test.go
  pkg/ddc/vineyard/replicas_test.go
  pkg/ddc/vineyard/transform.go
  pkg/ddc/vineyard/transform_test.go
  pkg/ddc/vineyard/utils.go
  pkg/ddc/vineyard/utils_test.go
  pkg/ddc/vineyard/worker_test.go
  pkg/utils/shell_pipes_test.go
Labels: needs-ok-to-test, approved

#3699 refactor: safe exec commands
  pkg/csi/plugins/nodeserver.go
  pkg/ddc/alluxio/operations/base.go
  pkg/ddc/efc/operations/base.go
  pkg/ddc/goosefs/operations/base.go
  pkg/ddc/jindo/operations/base.go
  pkg/ddc/jindocache/operations/base.go
  pkg/ddc/jindofsx/operations/base.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/thin/operations/base.go
  pkg/utils/cmdguard/exec.go
  pkg/utils/cmdguard/exec_pipes.go
  pkg/utils/cmdguard/exec_pipes_test.go
  pkg/utils/cmdguard/exec_test.go
  pkg/utils/helm/get.go
  pkg/utils/helm/helm.go
  pkg/utils/helm/helm_test.go
  pkg/utils/helm/utils.go
  pkg/utils/helm/utils_test.go
  pkg/utils/home.go
  pkg/utils/kubeclient/exec.go
  pkg/utils/kubectl/configmap.go
  pkg/utils/mount.go
  pkg/utils/shell_pipes.go
  pkg/utils/shell_pipes_test.go
Labels: lgtm, approved

#3703 Add enableServiceLinks to efc and juicefs
  charts/efc/templates/fuse/daemonset.yaml
  charts/efc/templates/master/statefulset.yaml
  charts/efc/templates/worker/statefulset.yaml
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefuleset.yaml
Labels: lgtm, approved

#3705 Build docker images for refactoring command
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3704 Add enableServiceLinks to thin and vineyard
  charts/thin/templates/fuse/daemonset.yaml
  charts/thin/templates/worker/statefuleset.yaml
  charts/vineyard/templates/fuse/daemonset.yaml
  charts/vineyard/templates/master/statefulset.yaml
  charts/vineyard/templates/worker/statefulset.yaml
Labels: lgtm, approved

#3593 update /pkg/ddc/goosefs/shutdown_test.go "2022" to "2023"
  pkg/ddc/goosefs/shutdown_test.go
Labels: needs-ok-to-test

#3617 update apache license
  pkg/common/webhook.go
Labels: lgtm, needs-ok-to-test, approved

#3553 modify License
  pkg/utils/capabilities_test.go
Labels: lgtm, needs-ok-to-test, approved

#3707 enhancement: upgrade to jindo cache engine
  charts/fluid/fluid/values.yaml
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#3711 Build docker images for data migrating
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3708 enhancement: auto discover runtime crds and dynamically enable/disable reconcilers
  cmd/dataset/app/dataset.go
  pkg/common/webhook.go
  pkg/controllers/deploy/runtime_controllers.go
  pkg/controllers/deploy/runtime_controllers_test.go
  pkg/controllers/v1alpha1/dataflow/dataflow_controller.go
  pkg/ddc/factory.go
  pkg/utils/capabilities_test.go
  pkg/utils/discovery/api_discover.go
  pkg/utils/discovery/api_discover_test.go
  pkg/utils/runtimes.go
  test/prow/testcases/juicefs/juicefs_minio.py
Labels: lgtm, approved

#3714 bugfix: fix fluid discovery init order
  cmd/dataset/app/dataset.go
  pkg/controllers/deploy/runtime_controllers.go
  pkg/controllers/v1alpha1/dataflow/dataflow_controller.go
  pkg/utils/discovery/api_discover.go
  pkg/utils/discovery/api_discover_test.go
Labels: lgtm, approved
