Repository fluid-cloudnative/fluid, pull requests merged in 2024-02, with the labels that each got.

#3715 Build for crd discovery
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3554 update license of pkg/ddc/efc/data_load.go
  pkg/ddc/efc/data_load.go
Labels: lgtm, needs-ok-to-test, approved

#3721 Fix webufs in prow e2e test
  test/prow/fluid/fluidapi.py
  test/prow/scale_runtime.py
  test/prow/testcases/alluxio/alluxio_dynamic_mountpoint.py
  test/prow/testcases/common/csi_stale_patch.py
  test/prow/testcases/common/dataset_pvc_subpath.py
Labels: lgtm, approved

#3716 remove kubectl for runtime and dataset controller
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
  docker/Dockerfile.webhook
  pkg/ddc/alluxio/master_internal.go
  pkg/ddc/alluxio/master_internal_test.go
  pkg/ddc/efc/master_internal.go
  pkg/ddc/efc/master_internal_test.go
  pkg/ddc/goosefs/master_internal.go
  pkg/ddc/goosefs/master_internal_test.go
  pkg/ddc/jindo/master_internal.go
  pkg/ddc/jindo/master_internal_test.go
  pkg/ddc/jindocache/master_internal.go
  pkg/ddc/jindocache/master_internal_test.go
  pkg/ddc/jindofsx/master_internal.go
  pkg/ddc/jindofsx/master_internal_test.go
  pkg/ddc/juicefs/master_internal.go
  pkg/ddc/juicefs/master_internal_test.go
  pkg/ddc/thin/master_internal.go
  pkg/ddc/vineyard/master_internal.go
  pkg/ddc/vineyard/master_internal_test.go
  pkg/utils/cmdguard/exec.go
  pkg/utils/cmdguard/exec_pipes.go
  pkg/utils/cmdguard/exec_pipes_test.go
  pkg/utils/kubeclient/configmap.go
  pkg/utils/kubeclient/configmap_test.go
Labels: lgtm, approved

#3557 modify license for file fluid/pkg/ddc/juicefs/dataset.go
  pkg/ddc/juicefs/dataset.go
Labels: lgtm, approved

#3561 add license to pkg/ddc/goosefs/worker_test.go
  pkg/ddc/goosefs/worker_test.go
Labels: lgtm, approved

#3567 add license
  pkg/ddc/jindofsx/shutdown.go
Labels: lgtm, needs-ok-to-test, approved

#3576 lyccnb pr
  pkg/ddc/juicefs/replicas_test.go
Labels: lgtm, needs-ok-to-test, approved

#3601 update the comments
  pkg/ddc/juicefs/type.go
Labels: needs-ok-to-test

#3728 Set the node-puhlish-method as symlink mode for vineyard runtime.
  pkg/ddc/jindofsx/shutdown.go
  pkg/ddc/vineyard/runtime_info.go
  pkg/ddc/vineyard/runtime_info_test.go
Labels: lgtm, needs-ok-to-test, approved

#3729 Build docker image for vineyardRuntime
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3731 Add Developer Certificate Of Origin
  CONTRIBUTING.md
Labels: lgtm, approved

#3633 Add License
  pkg/ddc/thin/status_test.go
Labels: lgtm, needs-ok-to-test, approved

#3718 fix parallel datamigrate pod anti affinity for the launcher(job) pod
  charts/fluid-datamigrate/juicefs/templates/job.yaml
  charts/fluid-datamigrate/juicefs/templates/statefulset.yaml
  pkg/dataoperation/constants.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/data_migrate_test.go
Labels: lgtm, approved

#3733 Add vineyard runtime to the fluid arch image.
  static/architecture.png
  static/concepts/concept.png
Labels: lgtm, needs-ok-to-test, approved

#3738 cherry-pick to 0.9: del metadata sync && del duplicate metrics (#3380)
  pkg/ddc/juicefs/cache.go
  pkg/ddc/juicefs/cache_test.go
  pkg/ddc/juicefs/metadata.go
  pkg/ddc/juicefs/operations/base.go
  pkg/ddc/juicefs/operations/base_test.go
Labels: lgtm, approved

#3734 Docker build for data migrating
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  integration/kubeflow/README.md
Labels: lgtm, approved

#3736 feat: allow setting kube client QPS and Burst
  cmd/alluxio/app/alluxio.go
  cmd/dataset/app/dataset.go
  cmd/efc/app/efc.go
  cmd/jindo/app/jindo.go
  cmd/juicefs/app/juicefs.go
  cmd/thin/app/thin.go
  cmd/vineyard/app/vineyard.go
  pkg/controllers/manager.go
Labels: lgtm, approved
