Repository fluid-cloudnative/fluid, pull requests merged in 2024-06, with the labels that each got.

#4106 Add or normalize License information of Task158
  pkg/ddc/alluxio/transform_permission_test.go
Labels: lgtm, needs-ok-to-test, approved

#3971 Change the image registry of vineyard runtime from docker hub to aliyun ACR
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/fluid/fluid/values.yaml
  charts/vineyard/templates/worker/statefulset.yaml
  charts/vineyard/values.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  docs/zh/samples/vineyard/vineyard_runtime.md
  pkg/common/vineyard.go
  pkg/ddc/vineyard/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#4109 Add license information to health_check.go
  pkg/ddc/alluxio/health_check.go
Labels: lgtm, needs-ok-to-test, approved

#4144 fix default value
  pkg/ddc/jindocache/transform.go
Labels: lgtm, approved

#4154 Build docker images for fixing jindo cache performance issue
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4153 Bump up the vineyard to v0.22.2
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/fluid/fluid/values.yaml
  charts/vineyard/values.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  docs/zh/samples/vineyard/vineyard_runtime.md
  pkg/common/vineyard.go
  pkg/ddc/vineyard/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#4120 Add apache license_format in fluid_ufs_scheme_test.go
  pkg/common/fluid_ufs_scheme_test.go
  pkg/utils/runtimes_test.go
  pkg/utils/webhook.go
Labels: lgtm, needs-ok-to-test, approved

#4121 Standardize License Information in mock_engine.go
  pkg/ddc/base/mock/mock_engine.go
Labels: lgtm, needs-ok-to-test, approved

#4125 Correcting License Information in 'pkg/ddc/efc/cache.go' due to Copyright Time Error
  pkg/ddc/efc/cache.go
Labels: lgtm, needs-ok-to-test, approved

#4159 Build docker images for vineyard 0.22
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4161 Build docker images for fixing transformers
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4148 addons: add dynamic mount examples
  addons/dynamic-mount/base/Dockerfile
  addons/dynamic-mount/base/build.sh
  addons/dynamic-mount/base/entrypoint.sh
  addons/dynamic-mount/base/inotify-fluid-config.ini
  addons/dynamic-mount/base/inotify.sh
  addons/dynamic-mount/base/mount-helper.sh
  addons/dynamic-mount/base/mount-passthrough-fuse.sh
  addons/dynamic-mount/base/prestop.sh
  addons/dynamic-mount/base/reconcile_mount_program_settings.py
  addons/dynamic-mount/juicefs/docker/Dockerfile.juicefs
  addons/dynamic-mount/juicefs/docker/mount.sh
Labels: lgtm, approved

#4132 Correct Copyright year in ./pkg/ddc/base/label.go
  pkg/ddc/base/label.go
Labels: lgtm, needs-ok-to-test, approved

#4163 bugfix: check corrupted mount point in utils.RemoveSymlink
  pkg/utils/symlink.go
Labels: lgtm, approved

#4128 modify copyright time
  pkg/ddc/base/template_engine_test.go
Labels: lgtm, needs-ok-to-test, approved

#4134 change time from 2022 to 2020
  pkg/ddc/base/template_engine.go
Labels: lgtm, needs-ok-to-test, approved

#4145 changed the time of Copyright in the operation.go file to 2023
  pkg/ddc/base/operation.go
Labels: lgtm, needs-ok-to-test, approved

#4168 refactor: rename `CreateUpdatePodForSchedulingHandler` to `FluidMutatingHandler`
  pkg/webhook/handler/add_scheduler.go
  pkg/webhook/handler/handler.go
  pkg/webhook/handler/mutating/mutating_handler.go
  pkg/webhook/handler/mutating/mutating_handler_test.go
  pkg/webhook/handler/mutating/utils.go
  pkg/webhook/handler/mutating/webhook.go
  pkg/webhook/handler/register.go
Labels: lgtm, approved

#4167 minorfix: pin libfuse version in dynamic mount example
  addons/dynamic-mount/base/Dockerfile
  addons/dynamic-mount/base/build.sh
  addons/dynamic-mount/base/entrypoint.sh
  addons/dynamic-mount/base/mount-passthrough-fuse.sh
  addons/dynamic-mount/base/reconcile_mount_program_settings.py
Labels: lgtm, approved

#4170 Refactor admission webhook handler registration for better error handling
  pkg/webhook/handler/register.go
Labels: lgtm, approved

#4171 refactor: avoid passing namespace to mutation functions
  pkg/webhook/handler/mutating/mutating_handler.go
  pkg/webhook/handler/mutating/mutating_handler_test.go
Labels: lgtm, approved

#4172 minorfix: carefully handle pod.namespace to avoid side effect
  pkg/webhook/handler/mutating/mutating_handler.go
Labels: lgtm, approved

#4173 Build docker images for refactoring webhook
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4175 feat: support multiround sidecar injection
  pkg/application/inject/fuse/container.go
  pkg/application/inject/fuse/container_test.go
  pkg/application/inject/fuse/injector.go
  pkg/application/inject/fuse/injector_test.go
  pkg/ddc/base/runtime_helper.go
  pkg/webhook/handler/mutating/mutating_handler.go
  pkg/webhook/handler/mutating/utils.go
  pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
  pkg/webhook/utils/runtime_info.go
Labels: lgtm, approved

#4149 add Apache License ./pkg/ddc/base/interface.go
  pkg/ddc/base/interface.go
Labels: lgtm, needs-ok-to-test, approved

#4176 docs: Correcting the usage steps of the CONTABUTING.md document
  CONTRIBUTING.md
Labels: lgtm, needs-ok-to-test, approved

#4138 move dataflow affinity logic to fluidapp controller
  api/v1alpha1/common.go
  charts/fluid-dataloader/alluxio/templates/job.yaml
  charts/fluid-dataloader/goosefs/templates/job.yaml
  charts/fluid-dataloader/jindo/templates/job.yaml
  charts/fluid-dataloader/jindocache/templates/job.yaml
  charts/fluid-dataloader/jindofsx/templates/job.yaml
  charts/fluid-dataloader/juicefs/templates/job.yaml
  charts/fluid-datamigrate/juicefs/templates/job.yaml
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid/fluid/templates/_helpers.tpl
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/fluid/fluid/templates/role/fluidapp/rbac.yaml
  charts/fluid/fluid/values.yaml
  cmd/dataset/app/dataset.go
  cmd/fluidapp/app/fluidapp.go
  docs/en/samples/application_controller.md
  docs/zh/samples/application_controller.md
  pkg/common/label.go
  pkg/controllers/v1alpha1/databackup/implement.go
  pkg/controllers/v1alpha1/databackup/status_handler.go
  pkg/controllers/v1alpha1/dataload/implement.go
  pkg/controllers/v1alpha1/dataload/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/implement.go
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/controllers/v1alpha1/dataprocess/implement.go
  pkg/controllers/v1alpha1/dataprocess/status_handler.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller.go
  pkg/controllers/v1alpha1/fluidapp/dataflowaffinity/dataflowaffinity_controller_test.go
  pkg/controllers/v1alpha1/fluidapp/fluidapp_controller.go
  pkg/ctrl/watch/dataopjob_manager.go
  pkg/ctrl/watch/op_job.go
  pkg/ctrl/watch/op_job_test.go
  pkg/ctrl/watch/pod.go
  pkg/ctrl/watch/pod_test.go
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
  pkg/dataflow/helper.go
  pkg/dataflow/helper_test.go
  pkg/dataoperation/constants.go
  pkg/dataoperation/interface.go
  pkg/dataoperation/mock.go
  pkg/dataoperation/operation_type.go
  pkg/ddc/alluxio/operate.go
  pkg/ddc/base/operation_helm.go
  pkg/ddc/efc/operate.go
  pkg/ddc/goosefs/operate.go
  pkg/ddc/jindo/operate.go
  pkg/ddc/jindocache/operate.go
  pkg/ddc/jindofsx/operate.go
  pkg/ddc/juicefs/operate.go
  pkg/ddc/thin/operate.go
  pkg/ddc/vineyard/operator.go
  pkg/utils/dataoperation.go
  pkg/utils/dataoperation_test.go
  pkg/utils/kubeclient/job.go
  pkg/utils/kubeclient/job_test.go
  test/prow/fluid/step_funcs.py
Labels: lgtm, approved

#4181 Build docker images for refactoring dataflow controller
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4116 Update utils.go
  pkg/ddc/alluxio/utils.go
Labels: lgtm, needs-ok-to-test, approved

#4184 minorfix: do not skip mutation for fluid pods
  pkg/webhook/handler/mutating/mutating_handler.go
Labels: lgtm, approved

#4185 bugfix: fix application controller manage pod lifecycle
  pkg/ctrl/watch/pod.go
  pkg/utils/annotations.go
  pkg/webhook/plugins/fusesidecar/fuse_sidecar.go
Labels: lgtm, approved

#4114 cm1
  pkg/ddc/alluxio/ufs.go
Labels: lgtm, approved, ok-to-test
