Repository fluid-cloudnative/fluid, pull requests merged in 2024-05, with the labels that each got.

#3973 Change the time
  api/v1alpha1/goosefsruntime_types.go
Labels: lgtm, needs-ok-to-test, approved

#3840 Change copyright date
  api/v1alpha1/dataset_types.go
Labels: lgtm, needs-ok-to-test, approved

#3861 change year
  pkg/controllers/v1alpha1/goosefs/implement.go
Labels: lgtm, needs-ok-to-test, approved

#3843 Task 81
  pkg/controllers/v1alpha1/dataflow/operations.go
Labels: lgtm, needs-ok-to-test, approved

#3844 task6-添加或规范License信息
  api/v1alpha1/dataprocess_types.go
Labels: lgtm, needs-ok-to-test, approved

#3884 changed CopyRight year from 2023 to 2021 of pkg/ctrl/watch/fake_runtime_reconciler.go
  pkg/ctrl/watch/fake_runtime_reconciler.go
Labels: lgtm, needs-ok-to-test, approved

#3845 Add Apache License to dataload_types.go
  api/v1alpha1/dataload_types.go
Labels: needs-ok-to-test, approved

#3847 fix copyright year infomation of ./cmd/efc/app/version.go
  cmd/efc/app/version.go
Labels: needs-ok-to-test, approved

#3849 correct Copyright data
  pkg/controllers/v1alpha1/alluxio/alluxio_runtime_controller.go
Labels: needs-ok-to-test, approved

#3850 Add the missing Apache License
  pkg/controllers/v1alpha1/databackup/databackup_controller_test.go
Labels: needs-ok-to-test, approved

#3851 correct Copyright data
  pkg/controllers/v1alpha1/databackup/databackup_controller.go
Labels: needs-ok-to-test, approved

#3855 modify year
  cmd/efc/app/efc.go
Labels: needs-ok-to-test, approved

#3856 normalize License information of ./cmd/csi/app/csi.go
  cmd/csi/app/csi.go
Labels: needs-ok-to-test, approved

#3857 modify year
  pkg/controllers/v1alpha1/alluxio/implement.go
Labels: needs-ok-to-test, approved

#3858 complete license in zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: needs-ok-to-test, approved

#3863 controll->control
  docs/en/samples/data_warmup.md
Labels: needs-ok-to-test, approved

#3903 Corrected the misspelled 'beacuse' to 'because' in file fluid/pkg/ddc…
  pkg/ddc/alluxio/transform_api_gateway_test.go
Labels: lgtm, needs-ok-to-test, approved

#3872 Update Copyright Date
  pkg/ddc/base/base_suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3878 modify the License in api/v1alpha1/status.go, change 2022 to 2020
  api/v1alpha1/status.go
Labels: lgtm, needs-ok-to-test, approved

#3873 Correct copyright year in transform_volumes_test.go
  pkg/ddc/alluxio/transform_volumes_test.go
Labels: lgtm, needs-ok-to-test, approved

#3990 fix copyright year
  pkg/common/label.go
Labels: lgtm, needs-ok-to-test, approved

#3875 fix licence in ./pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
  pkg/controllers/v1alpha1/goosefs/goosefs_runtime_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3876 modify license
  pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3883 fix the copyright year of the file 'hack/sdk/main.go'
  hack/sdk/main.go
Labels: lgtm, needs-ok-to-test, approved

#3885 Specify License for./pkg/ddc/alluxio/utils_test.go
  pkg/ddc/alluxio/utils_test.go
Labels: lgtm, needs-ok-to-test, approved

#3891 correct the date of Copyright
  pkg/ddc/alluxio/transform_test.go
Labels: lgtm, needs-ok-to-test, approved

#3892 Add Copyright to ./pkg/controllers/v1alpha1/jindo/suite_test.go
  pkg/controllers/v1alpha1/jindo/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3894 Standardize License Information in file 'pkg/controllers/v1alpha1/dat…
  pkg/controllers/v1alpha1/dataprocess/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3896 Modify the license of ./pkg/ddc/alluxio/runtime_info_test.go
  pkg/ddc/alluxio/runtime_info_test.go
Labels: lgtm, needs-ok-to-test, approved

#3899 有Apache License的通告声明，也有Copyright，但 Copyright时间有误
  pkg/ddc/alluxio/transform_ufs_test.go
Labels: lgtm, needs-ok-to-test, approved

#3901 Fix a copyright date error
  api/v1alpha1/groupversion_info.go
Labels: lgtm, needs-ok-to-test, approved

#3907 fix typo of file operation.go
  pkg/ddc/base/operation.go
Labels: lgtm, needs-ok-to-test, approved

#3908 modify the license info in pkg/ddc/alluxio/backup_data.go
  pkg/ddc/alluxio/backup_data.go
Labels: lgtm, needs-ok-to-test, approved

#3911 fix copyright year of a file
  pkg/dataload/constants.go
Labels: lgtm, needs-ok-to-test, approved

#3914 modify copyright year in cmd/alluxio/main.go
  cmd/alluxio/main.go
Labels: lgtm, needs-ok-to-test, approved

#3916 fix copyright date error
  pkg/controllers/v1alpha1/dataload/implement_test.go
Labels: lgtm, needs-ok-to-test, approved

#3919 fix copyright date error
  pkg/ddc/base/operation_lock_test.go
Labels: lgtm, needs-ok-to-test, approved

#3920 change the wrong year of copyright
  pkg/ddc/alluxio/operations/base.go
Labels: lgtm, needs-ok-to-test, approved

#3922 fix copyright
  pkg/controllers/v1alpha1/efc/implement.go
Labels: lgtm, needs-ok-to-test, approved

#3925 change the wrong year of copyright
  pkg/ctrl/watch/mutatingwebhookconfiguration_test.go
Labels: lgtm, needs-ok-to-test, approved

#3926 Add missing Copyright info in cmd/webhook/app/init.go
  cmd/webhook/app/init.go
Labels: lgtm, needs-ok-to-test, approved

#3927 lab1-time
  api/v1alpha1/jindoruntime_types.go
Labels: lgtm, needs-ok-to-test, approved

#3929 Modify Apache License CopyRight
  pkg/common/critical_fuse_pod_test.go
Labels: lgtm, needs-ok-to-test, approved

#3931 Modify the year of the Copyright of the Apache License in ./pkg/ddc/alluxio/cache.go
  pkg/ddc/alluxio/cache.go
Labels: lgtm, needs-ok-to-test, approved

#3934 My dev pull
  pkg/ddc/efc/create_volume.go
Labels: lgtm, needs-ok-to-test, approved

#3938 changing the apach liscense year of file './pkg/controllers/v1alpha1/juicefs/suite_test.go'
  pkg/controllers/v1alpha1/juicefs/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3940 modified the lisence
  pkg/dataload/value.go
Labels: lgtm, needs-ok-to-test, approved

#3943 fix Copyright time in cmd/jindo/main.go
  cmd/jindo/main.go
Labels: lgtm, needs-ok-to-test, approved

#3945 modify the year
  pkg/utils/webhook/generator/util.go
Labels: lgtm, needs-ok-to-test, approved

#3946 add copyright
  api/v1alpha1/vineyardruntime_types.go
Labels: lgtm, needs-ok-to-test, approved

#3949 modify license
  pkg/ddc/alluxio/metadata.go
Labels: lgtm, needs-ok-to-test, approved

#3955 modified: check_fuse_default.go 2021 --> 2023
  pkg/application/inject/fuse/poststart/check_fuse_default.go
Labels: lgtm, needs-ok-to-test, approved

#3957 Modify theCopyRight
  pkg/utils/mountinfo/mountinfo.go
Labels: lgtm, needs-ok-to-test, approved

#3958 Fix the copyright year of Apache License in pkg/ddc/alluxio/ufs_ internal.go
  pkg/ddc/alluxio/ufs_internal.go
Labels: lgtm, needs-ok-to-test, approved

#3962 Fix typo in cmd\dataset\app\dataset.go
  cmd/dataset/app/dataset.go
Labels: lgtm, needs-ok-to-test, approved

#3963 modify year in Copyright 2023->2020
  pkg/ddc/alluxio/master_internal.go
Labels: lgtm, needs-ok-to-test, approved

#3965 Fix copyright year in ./cmd/dataset/app/init.go
  cmd/dataset/app/init.go
Labels: lgtm, needs-ok-to-test, approved

#3976 modified the copyright year
  pkg/common/storage.go
Labels: lgtm, needs-ok-to-test, approved

#3977 211220171 马旭佳
  cmd/csi/main.go
Labels: lgtm, needs-ok-to-test, approved

#3984 Task 26: Changing the time from 2021 to 2022
  cmd/dataset/app/dataset.go
Labels: lgtm, needs-ok-to-test, approved

#3985 add copyright condition2
  pkg/ddc/alluxio/transform_resources_test.go
Labels: lgtm, needs-ok-to-test, approved

#3989 correct reconcilation to reconciliation in 84:144 and 85:137
  cmd/vineyard/app/vineyard.go
Labels: lgtm, needs-ok-to-test, approved

#3993 modify copyright year
  pkg/ddc/alluxio/deprecated_label.go
Labels: lgtm, needs-ok-to-test, approved

#3997 corrected "Compatiable" to "Compatible"
  pkg/ddc/goosefs/hcfs.go
Labels: lgtm, needs-ok-to-test, approved

#4000 correct copyright in ./pkg/ddc/alluxio/deprecated_label_test.go
  pkg/ddc/alluxio/deprecated_label_test.go
Labels: lgtm, needs-ok-to-test, approved

#4001 Modified the copyright date 2021 -> 2022
  cmd/dataset/app/version.go
Labels: lgtm, needs-ok-to-test, approved

#4005 this pr is to add change the year of copyright from 2023 to 2021
  pkg/ddc/alluxio/health_check_test.go
Labels: lgtm, needs-ok-to-test, approved

#4006 modify <year> from 2021 to 2022
  cmd/csi/app/init.go
Labels: lgtm, needs-ok-to-test, approved

#4013 This pr is to add License of script_gen_helper.go
  pkg/application/inject/fuse/poststart/script_gen_helper.go
Labels: lgtm, needs-ok-to-test, approved

#4014 add and modify infomation for check_fuse_unprivileged.go
  pkg/application/inject/fuse/poststart/check_fuse_unprivileged.go
Labels: lgtm, needs-ok-to-test, approved

#4015 correct the license year of ./pkg/ddc/alluxio/runtime_info.go
  pkg/ddc/alluxio/runtime_info.go
Labels: lgtm, needs-ok-to-test, approved

#4017 Change the time of the Copyright in pkg/ddc/alluxio/transform_volumes.go
  pkg/ddc/alluxio/transform_volumes.go
Labels: lgtm, needs-ok-to-test, approved

#4020 Add Copyright
  pkg/common/fluid_ufs_scheme.go
Labels: lgtm, needs-ok-to-test, approved

#4026 Standard Licence Information of No.138
  pkg/ddc/alluxio/operations/cached.go
Labels: lgtm, needs-ok-to-test, approved

#4028 This pr is to Fix wrong time of Copyright
  pkg/ddc/alluxio/status.go
Labels: lgtm, needs-ok-to-test, approved

#4030 corrected 'Prometheous' to 'Prometheus'
  docs/en/operation/monitoring.md
Labels: lgtm, needs-ok-to-test, approved

#4031 更改 ./pkg/ddc/alluxio/operations/local_test.go文件中license信息
  pkg/ddc/alluxio/operations/local_test.go
Labels: lgtm, needs-ok-to-test, approved

#4063 Remove unused function "AssignNodesToDataset" and "AssignNodesToCache"
  pkg/ddc/alluxio/node.go
  pkg/ddc/alluxio/node_test.go
  pkg/ddc/base/engine.go
  pkg/ddc/efc/node.go
  pkg/ddc/efc/node_test.go
  pkg/ddc/goosefs/node.go
  pkg/ddc/goosefs/node_test.go
  pkg/ddc/jindo/node.go
  pkg/ddc/jindo/node_test.go
  pkg/ddc/jindocache/node.go
  pkg/ddc/jindocache/node_test.go
  pkg/ddc/jindofsx/node.go
  pkg/ddc/jindofsx/node_test.go
  pkg/ddc/juicefs/node.go
  pkg/ddc/juicefs/node_test.go
  pkg/ddc/thin/node.go
  pkg/ddc/thin/node_test.go
  pkg/ddc/vineyard/node.go
  pkg/ddc/vineyard/node_test.go
  pkg/utils/dataset/lifecycle/assigncache_test.go
  pkg/utils/dataset/lifecycle/schedule.go
  pkg/utils/dataset/lifecycle/schedule_test.go
  pkg/utils/dataset/lifecycle/schedule_utils.go
  pkg/utils/dataset/lifecycle/schedule_utils_test.go
Labels: lgtm, approved

#3821 modify "seperates" to "separates"
  docs/en/samples/juicefs_for_s3.md
Labels: lgtm, needs-ok-to-test, approved

#3432 Feature: support dynamic mount for ossfs
  addons/cephfs/docker/fluid_config_init.py
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4-zh_CN.md
  addons/cubefs/v2.4/dev-guide/cubefs-v2.4.md
  addons/cubefs/v2.4/docker/fluid_config_init.py
  addons/cubefs/v3.2/dev-guide/cubefs-v3.2-zh_CN.md
  addons/cubefs/v3.2/dev-guide/cubefs-v3.2.md
  addons/cubefs/v3.2/docker/fluid_config_init.py
  addons/dynamic-mount/ossfs/docker/Dockerfile
  addons/dynamic-mount/ossfs/docker/build.sh
  addons/dynamic-mount/ossfs/docker/inotify.sh
  addons/dynamic-mount/ossfs/docker/mount_and_umount.py
  addons/dynamic-mount/ossfs/docker/umount.sh
  addons/dynamic-mount/ossfs/runtime-profile.yaml
  addons/glusterfs/dev-guide/glusterfs-zh_CN.md
  addons/glusterfs/dev-guide/glusterfs.md
  addons/glusterfs/docker/entrypoint.py
  addons/nfs/dev-guide/nfs-zh_CN.md
  addons/nfs/dev-guide/nfs.md
  addons/nfs/docker/fluid_config_init.py
  api/v1alpha1/dataset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/templates/role/thin/rbac.yaml
  charts/thin/templates/fuse/daemonset.yaml
  docs/zh/samples/thinruntime.md
  pkg/controllers/v1alpha1/efc/efcruntime_controller.go
  pkg/controllers/v1alpha1/jindo/jindoruntime_controller.go
  pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go
  pkg/controllers/v1alpha1/thinruntime/thinruntime_controller.go
  pkg/ctrl/watch/dataset.go
  pkg/ctrl/watch/manager.go
  pkg/ddc/thin/operations/base.go
  pkg/ddc/thin/transform_config.go
  pkg/ddc/thin/ufs.go
  pkg/ddc/thin/ufs_test.go
  pkg/ddc/thin/util.go
Labels: lgtm, needs-ok-to-test, approved

#3936 corrected "produciton" to "production"
  ROADMAP.md
Labels: lgtm, needs-ok-to-test, approved

#3942 have changed the year to the right one
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3954 correct Apache License year at implement.go
  pkg/controllers/v1alpha1/juicefs/implement.go
Labels: lgtm, needs-ok-to-test, approved

#4003 Upgrade to golang 1.21.8
  .circleci/config.yml
  .github/workflows/go.yml
  .travis.yml
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
  docker/Dockerfile.webhook
  go.mod
  pkg/ddc/vineyard/operations/base_test.go
  pkg/utils/kubeclient/pod_test.go
  pkg/utils/webhook_test.go
  pkg/webhook/plugins/plugins_impl_test.go
Labels: lgtm, approved

#3924 2022->2021
  api/v1alpha1/juicefsruntime_types.go
Labels: lgtm, needs-ok-to-test, approved

#3951 update suite_test.go
  pkg/controllers/v1alpha1/efc/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3956 Add copyright in rumtime_controller.go
  pkg/controllers/runtime_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3959 Modified the copyright year
  pkg/common/webhook.go
Labels: lgtm, needs-ok-to-test, approved

#3960 ri.go
  pkg/common/runtime_identity.go
Labels: lgtm, needs-ok-to-test, approved

#3964 change COPYRIGHT 2023 to 2020
  pkg/ddc/alluxio/transform_fuse.go
Labels: lgtm, needs-ok-to-test, approved

#4070 Use generic Set for volumeLock
  pkg/utils/volume_lock.go
Labels: lgtm, approved

#4071 Build docker images for K8s 1.26.10 , controller-runtime 0.14.7, golang 1.21
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4052 fix code scaning alerts —— Incomplete regular expression for hostnames
  pkg/common/label.go
  pkg/common/label_test.go
Labels: lgtm, approved

#4004 modify the time of copyright
  pkg/csi/plugins/controller.go
Labels: lgtm, needs-ok-to-test, approved

#4008 modify <year> from 2023 to 2022
  pkg/csi/plugins/driver.go
Labels: lgtm, needs-ok-to-test, approved

#4010 update recover.go
  pkg/csi/recover/recover.go
Labels: lgtm, needs-ok-to-test, approved

#4018 correct Copyright
  pkg/application/inject/fuse/poststart/check_fuse_app.go
Labels: lgtm, needs-ok-to-test, approved

#4019 correct Copyright
  pkg/ddc/alluxio/report.go
Labels: lgtm, needs-ok-to-test, approved

#4021 Add or standardize license information at the beginning of the file.
  pkg/ctrl/watch/pod.go
Labels: lgtm, needs-ok-to-test, approved

#4022 在文件头部添加或规范License信息 Task-156
  pkg/ddc/alluxio/transform_optimization_test.go
Labels: lgtm, needs-ok-to-test, approved

#4027 Change the time of the Copyright in pkg/ddc/alluxio/transform_resources.go
  pkg/ddc/alluxio/transform_resources.go
Labels: lgtm, needs-ok-to-test, approved

#4032 task139
  pkg/ddc/alluxio/operations/conf.go
Labels: lgtm, needs-ok-to-test, approved

#4033 Add or normalize License information
  pkg/application/inject/fuse/mutator/mutator.go
Labels: lgtm, needs-ok-to-test, approved

#4045 cmd/jindo/app/init.go.fix
  cmd/jindo/app/init.go
Labels: lgtm, needs-ok-to-test, approved

#3972 corrected copyright info in /pkg/ddc/alluxio/transform_ufs.go
  pkg/ddc/alluxio/transform_ufs.go
Labels: lgtm, needs-ok-to-test, approved

#3978 Standardize the License of /pkg/common/efc.go
  pkg/common/efc.go
Labels: lgtm, needs-ok-to-test, approved

#4009 License of suite_test.go is updated.
  pkg/controllers/v1alpha1/jindo/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#4083 Update docker file golang 1.12.10
  addons/dynamic-mount/ossfs/docker/Dockerfile
  api/v1alpha1/juicefsruntime_types.go
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
  docker/Dockerfile.webhook
  pkg/controllers/v1alpha1/dataset/dataset_controller.go
Labels: lgtm, approved

#4096 Fix security issue introduced in vineyard samples
  docs/en/samples/vineyard/vineyard_runtime.md
  docs/zh/samples/vineyard/vineyard_runtime.md
  samples/vineyard/prepare-data.yaml
  samples/vineyard/prepare-data/prepare-data.py
Labels: lgtm, needs-ok-to-test, approved

#4098 Build docker images for golang 1.12.10
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3829 support dataflow affinity
  api/v1alpha1/common.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid-databackup/alluxio/templates/databackup.yaml
  charts/fluid-databackup/alluxio/values.yaml
  charts/fluid-dataprocess/common/templates/job.yaml
  charts/fluid-dataprocess/common/values.yaml
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  pkg/common/constants.go
  pkg/controllers/v1alpha1/databackup/status_handler.go
  pkg/controllers/v1alpha1/dataload/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/controllers/v1alpha1/dataprocess/status_handler.go
  pkg/databackup/value.go
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
  pkg/dataflow/helper.go
  pkg/dataflow/helper_test.go
  pkg/dataprocess/generate_values.go
  pkg/dataprocess/processor_types.go
  pkg/dataprocess/value.go
  pkg/ddc/alluxio/backup_data.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/alluxio/process_data.go
  pkg/ddc/efc/data_process.go
  pkg/ddc/goosefs/backup_data.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/goosefs/load_data_test.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindo/load_data_test.go
  pkg/ddc/jindocache/load_data.go
  pkg/ddc/jindocache/load_data_test.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/jindofsx/load_data_test.go
  pkg/ddc/jindofsx/process_data.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_load_test.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/data_migrate_test.go
  pkg/ddc/juicefs/data_process.go
  pkg/ddc/thin/data_process.go
  pkg/ddc/vineyard/process_data.go
  pkg/utils/affinity.go
  pkg/utils/affinity_test.go
  pkg/utils/fluid.go
  pkg/utils/kubeclient/job.go
Labels: lgtm, approved

#4099 Fix crd generation issue
  api/v1alpha1/common.go
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_databackups.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataloads.yaml
  charts/fluid/fluid/crds/data.fluid.io_datamigrates.yaml
  charts/fluid/fluid/crds/data.fluid.io_dataprocesses.yaml
  config/crd/bases/data.fluid.io_databackups.yaml
  config/crd/bases/data.fluid.io_dataloads.yaml
  config/crd/bases/data.fluid.io_datamigrates.yaml
  config/crd/bases/data.fluid.io_dataprocesses.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  pkg/dataflow/affinity.go
  pkg/dataflow/affinity_test.go
Labels: lgtm

#4036 Standard Licence Information of No.140
  pkg/ddc/alluxio/operations/local.go
Labels: lgtm, needs-ok-to-test, approved

#4038 Standardize Apache License for ./pkg/ddc/engine.go.
  pkg/ddc/base/engine.go
Labels: lgtm, needs-ok-to-test, approved

#4105 Add the random_state for train_test_split in vineyard samples.
  samples/vineyard/preprocess-data/preprocess-data.py
Labels: lgtm, needs-ok-to-test, approved

#4037 fix: modify the date
  pkg/ddc/alluxio/ufs_test.go
Labels: lgtm, needs-ok-to-test, approved

#4042 Fix the date error in License for cmd/jindo/app/jindo.go
  cmd/jindo/app/jindo.go
Labels: lgtm, needs-ok-to-test, approved

#4043 fix copyright year from 2022 to 2020
  pkg/ddc/base/volume.go
Labels: lgtm, needs-ok-to-test, approved

#3982 Support to configure the cache size of vineyard fuse
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/vineyard/templates/fuse/daemonset.yaml
  charts/vineyard/templates/worker/statefulset.yaml
  charts/vineyard/values.yaml
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  docs/en/dev/api_doc.md
  docs/en/samples/vineyard/configure_cache_size_of_vineyard_fuse.md
  docs/zh/dev/api_doc.md
  pkg/ddc/vineyard/const.go
  pkg/ddc/vineyard/transform.go
  pkg/ddc/vineyard/transform_resources_test.go
  pkg/ddc/vineyard/transform_test.go
  pkg/ddc/vineyard/type.go
Labels: lgtm, needs-ok-to-test, approved

#4126 upgrade jindocache to 6.4.0 version
  charts/fluid/fluid/values.yaml
  charts/jindocache/CHANGELOG.md
  charts/jindocache/Chart.yaml
  charts/jindocache/values.yaml
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_fuse_test.go
  pkg/ddc/jindocache/transform_test.go
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#4135 Build docker images for dataflow,
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4047 modify License of cmd/goosefs/app/version.go
  cmd/goosefs/app/version.go
Labels: lgtm, needs-ok-to-test, approved

#4141 Fix the inconsistent rpc socket port with assigned port in vineyard worker.
  charts/vineyard/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4130 refactor: remove deprecated data operation interface
  pkg/ddc/alluxio/data_migrate.go
  pkg/ddc/alluxio/load_data.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/base/engine.go
  pkg/ddc/base/load_data.go
  pkg/ddc/base/migrate_data.go
  pkg/ddc/base/mock/mock_engine.go
  pkg/ddc/base/operation.go
  pkg/ddc/base/operation_lock.go
  pkg/ddc/base/operation_lock_test.go
  pkg/ddc/base/template_engine_test.go
  pkg/ddc/efc/data_load.go
  pkg/ddc/efc/data_load_test.go
  pkg/ddc/efc/data_migrate.go
  pkg/ddc/goosefs/data_migrate.go
  pkg/ddc/goosefs/load_data.go
  pkg/ddc/goosefs/load_data_test.go
  pkg/ddc/jindo/data_migrate.go
  pkg/ddc/jindo/load_data.go
  pkg/ddc/jindo/load_data_test.go
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/data_migrate.go
  pkg/ddc/jindocache/load_data.go
  pkg/ddc/jindocache/load_data_test.go
  pkg/ddc/jindofsx/const.go
  pkg/ddc/jindofsx/data_migrate.go
  pkg/ddc/jindofsx/load_data.go
  pkg/ddc/jindofsx/load_data_test.go
  pkg/ddc/juicefs/data_load.go
  pkg/ddc/juicefs/data_load_test.go
  pkg/ddc/juicefs/data_migrate.go
  pkg/ddc/juicefs/data_migrate_test.go
  pkg/ddc/thin/dataload.go
  pkg/ddc/thin/dataload_test.go
  pkg/ddc/thin/datamigrate.go
  pkg/ddc/thin/referencedataset/dataload.go
  pkg/ddc/thin/referencedataset/datamigrate.go
  pkg/ddc/thin/runtime_info.go
  pkg/ddc/vineyard/data_migrate.go
  pkg/ddc/vineyard/load_data.go
  pkg/ddc/vineyard/runtime_info.go
Labels: lgtm, approved

#4143 Build docker image for code refactoring
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4049 no.154
  pkg/ddc/alluxio/transform_init_users_test.go
Labels: lgtm, needs-ok-to-test, approved

#4139 Fix NPE of runtime controller
  pkg/controllers/runtime_controller.go
Labels: lgtm, approved

#4044 this pr is to fix a wrong time of Copyright
  pkg/ddc/alluxio/types.go
Labels: lgtm, needs-ok-to-test, approved

#4051 correct the year of copyright
  pkg/ddc/alluxio/types_test.go
Labels: lgtm, needs-ok-to-test, approved

#4075 This pr is to add a Copyright to normalize the License
  cmd/webhook/app/version.go
Labels: lgtm, needs-ok-to-test, approved

#4053 Standardize License Information
  pkg/ddc/alluxio/create_volume.go
Labels: lgtm, needs-ok-to-test, approved

#4056 This pr is to add license to ./pkg/common/constants.go
  pkg/common/constants.go
Labels: lgtm, needs-ok-to-test, approved

#4055 the modification of the time
  pkg/ddc/base/operation_lock.go
Labels: lgtm, needs-ok-to-test, approved

#4060 corrected a word
  pkg/ddc/goosefs/transform_api_gateway_test.go
Labels: lgtm, needs-ok-to-test, approved

#4061 add license
  cmd/webhook/app/webhook.go
Labels: lgtm, needs-ok-to-test, approved

#4062 modify year of license in pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/engine.go
Labels: lgtm, needs-ok-to-test, approved

#4064 This pr is to change the time of Copyright
  pkg/ddc/alluxio/transform.go
Labels: lgtm, needs-ok-to-test, approved

#4065 This pr is to correct the year of the License
  pkg/ddc/alluxio/const.go
Labels: lgtm, needs-ok-to-test, approved

#4066 Changed Copyright date from 2023 to 2020.
  pkg/ddc/alluxio/dataset.go
Labels: lgtm, needs-ok-to-test, approved

#4069 Standardized license information of cmd/thin/app/thin.go
  cmd/thin/app/thin.go
Labels: lgtm, needs-ok-to-test, approved

#4074 add License to ./pkg/common/alluxio.go
  pkg/common/alluxio.go
Labels: lgtm, needs-ok-to-test, approved

#4076 修改 ./pkg/ddc/base/log_test.go中的 copyright日期
  pkg/ddc/base/log_test.go
Labels: lgtm, needs-ok-to-test, approved

#4079 Fix copyright year in api_gateway.go
  pkg/ddc/alluxio/api_gateway.go
Labels: lgtm, needs-ok-to-test, approved

#4089 task199
  pkg/ddc/efc/const.go
Labels: lgtm, needs-ok-to-test, approved

#4094 This pr is to change the time in pkg/ddc/alluxio/transform_fuse_test.go in lab1 task 151
  pkg/ddc/alluxio/transform_fuse_test.go
Labels: lgtm, needs-ok-to-test, approved

#4095 This pr is to change the time of the file transform_hadoop_config.go in task 152.
  pkg/ddc/alluxio/transform_hadoop_config.go
Labels: lgtm, needs-ok-to-test, approved

#4146 Build docker image for fixing NPE
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved
