Repository fluid-cloudnative/fluid, pull requests merged in 2024-04, with the labels that each got.

#3781 Update installation guide for v1.0.0
  docs/en/userguide/install.md
  docs/zh/userguide/install.md
Labels: lgtm, approved

#3782 standardize the License information in the header of the file
  pkg/controllers/operation_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3784 fix jindoruntime local mount point
  pkg/ddc/jindocache/transform.go
Labels: lgtm, approved

#3783 Support to configure the image of vineyard component by env.
  charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
  charts/fluid/fluid/values.yaml
  pkg/common/vineyard.go
  pkg/ddc/vineyard/transform.go
  pkg/ddc/vineyard/transform_test.go
  pkg/ddc/vineyard/utils.go
Labels: lgtm, needs-ok-to-test

#3786 fix typo in monitoring.md
  docs/zh/operation/monitoring.md
Labels: lgtm, needs-ok-to-test, approved

#3788 Fixes #3787 about typo in dataprocess_types.go
  api/v1alpha1/dataprocess_types.go
Labels: lgtm, needs-ok-to-test, approved

#3792 Fix copyright date in comment lines
  cmd/alluxio/app/version.go
Labels: lgtm, needs-ok-to-test, approved

#3800 Build docker images for jindocache with pvc support
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3811 JindoCache supports user-defined names for mounting secret
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_test.go
Labels: lgtm, approved

#3789 Fix copyright year in init.go
  cmd/alluxio/app/init.go
Labels: lgtm, needs-ok-to-test, approved

#3820 Build docker images for user specified secret
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3779 Add the tutotial about how to use vineyard runtime to accelerate the kubeflow pipelines.
  docs/en/samples/vineyard/accelerate_kubeflow_pipelines.md
  docs/en/samples/vineyard/vineyard_runtime.md
  docs/zh/samples/vineyard/accelerate_kubeflow_pipelines.md
  docs/zh/samples/vineyard/vineyard_runtime.md
  samples/vineyard/Dockerfile
  samples/vineyard/Makefile
  samples/vineyard/pipeline-with-vineyard.py
  samples/vineyard/pipeline-with-vineyard.yaml
  samples/vineyard/pipeline.py
  samples/vineyard/pipeline.yaml
  samples/vineyard/prepare-data.yaml
  samples/vineyard/prepare-data/prepare-data.py
  samples/vineyard/preprocess-data/preprocess-data.py
  samples/vineyard/rbac.yaml
  samples/vineyard/test-data/test-data.py
  samples/vineyard/train-data/train-data.py
Labels: lgtm, needs-ok-to-test, approved

#3812 Refine the vineyard runtime doc and add a section about data sharing.
  docs/en/samples/vineyard/vineyard_runtime.md
  docs/zh/samples/vineyard/vineyard_runtime.md
Labels: lgtm, needs-ok-to-test, approved

#3826 Fix `fluid.io/node-publish-method` typo
  pkg/common/label.go
  pkg/ddc/vineyard/runtime_info.go
  pkg/ddc/vineyard/runtime_info_test.go
  test/prow/testcases/common/csi_nodepublish_symlink.py
Labels: lgtm, approved

#3780 correct the year in the copyright statement of pkg/common/volume.go
  pkg/common/volume.go
Labels: lgtm, needs-ok-to-test, approved

#3837 Build docker images for fixing node-publishing-method
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3825 Update change log for v1.0
  CHANGELOG.md
Labels: lgtm, approved

#3860 Correct juicefs worker name and remove unused RBAC
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
  charts/juicefs/templates/worker/statefulset.yaml
Labels: lgtm, approved

#3823 fix type in cmd/thin/app/thin.go
  cmd/thin/app/thin.go
Labels: lgtm, needs-ok-to-test, approved

#3818 fix a spell mistake--package
  hack/sdk/post-gen.py
Labels: lgtm, needs-ok-to-test, approved

#3864 Build docker images for fixing juicefs worker name
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3867 Readd daemonsets rbac permission
  charts/fluid/fluid/templates/role/dataset/rbac.yaml
Labels: lgtm, approved

#3868 Update security info
  README-zh_CN.md
  README.md
  SECURITY.md
Labels: lgtm, approved

#3879 Update What's new in ReadMe for v1.0.0 release.
  README-zh_CN.md
  README.md
Labels: lgtm, approved

#3886 Prepare 1.0.1
  Makefile
  charts/fluid/fluid/Chart.yaml
Labels: lgtm, approved

#3790 Copyright时间有误，2022改为2023
  cmd/efc/main.go
Labels: lgtm, needs-ok-to-test, approved

#3794 Add or standardize license information
  pkg/controllers/v1alpha1/jindo/implement.go
Labels: lgtm, approved, ok-to-test

#3801 Finish task 105 add license information
  pkg/csi/updatedbconf/updatedbconf_test.go
Labels: lgtm, needs-ok-to-test, approved

#3802 add license
  pkg/controllers/manager.go
Labels: lgtm, needs-ok-to-test, approved

#3803 license
  pkg/controllers/namespace_test.go
Labels: lgtm, needs-ok-to-test, approved

#3806 fix typo in dataset_auto_scaling.md
  docs/zh/operation/dataset_auto_scaling.md
Labels: lgtm, needs-ok-to-test, approved

#3808 fix typo:corrected Exmaple to Example
  charts/vineyard/values.yaml
Labels: lgtm, needs-ok-to-test, approved

#3810 拼写错误纠正
  docs/en/samples/use_encryptoptions.md
Labels: lgtm, needs-ok-to-test, approved

#3815 [DOC] fix typo in cmd\alluxio\app\alluxio.go
  cmd/alluxio/app/alluxio.go
Labels: lgtm, needs-ok-to-test, approved

#3816 modify the date
  pkg/controllers/v1alpha1/dataload/implement.go
Labels: lgtm, needs-ok-to-test, approved

#3854 modify year
  api/v1alpha1/common.go
Labels: lgtm, needs-ok-to-test, approved

#3953 finish fixed ./pkg/ddc/alluxio/delete_volume.go
  pkg/ddc/alluxio/delete_volume.go
Labels: lgtm, needs-ok-to-test, approved

#3831 spoken corrected
  cmd/jindo/app/jindo.go
Labels: lgtm, needs-ok-to-test, approved

#3974 fix jindo rbac remove secret get
  charts/fluid/fluid/templates/role/jindo/rbac.yaml
Labels: lgtm, approved

#3732 support parallel tasks for cron datamigrate
  charts/fluid-datamigrate/juicefs/templates/cronjob.yaml
  charts/fluid-datamigrate/juicefs/templates/statefulset.yaml
  docs/zh/samples/juicefs/juicefs_data_migrate.md
  pkg/controllers/v1alpha1/datamigrate/status_handler.go
  pkg/controllers/v1alpha1/datamigrate/status_handler_test.go
  pkg/ddc/base/operation.go
  pkg/utils/kubeclient/job.go
Labels: lgtm, approved

#3966 lab1-2 lmy first
  pkg/ddc/alluxio/types_selector.go
Labels: lgtm, needs-ok-to-test, approved

#3833 Task4 - 添加或规范License信息
  api/v1alpha1/databackup_types.go
Labels: lgtm, needs-ok-to-test, approved

#3836 fix typo in dataset_sharedOptions.md
  docs/en/samples/dataset_sharedOptions.md
Labels: lgtm, needs-ok-to-test, approved

#3839 add licenses to source code
  pkg/dataoperation/mock.go
Labels: lgtm, needs-ok-to-test, approved

#3981 Support to configure the networkMode and podMetadata of vineyard components.
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/swagger.json
  api/v1alpha1/vineyardruntime_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/fluid/fluid/crds/data.fluid.io_vineyardruntimes.yaml
  charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
  charts/fluid/fluid/values.yaml
  charts/vineyard/templates/fuse/daemonset.yaml
  charts/vineyard/templates/master/statefulset.yaml
  charts/vineyard/templates/worker/statefulset.yaml
  charts/vineyard/values.yaml
  cmd/vineyard/app/vineyard.go
  config/crd/bases/data.fluid.io_vineyardruntimes.yaml
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
  pkg/ddc/vineyard/master_internal.go
  pkg/ddc/vineyard/master_internal_test.go
  pkg/ddc/vineyard/port_parser.go
  pkg/ddc/vineyard/port_parser_test.go
  pkg/ddc/vineyard/shut_down.go
  pkg/ddc/vineyard/shut_down_test.go
  pkg/ddc/vineyard/transform.go
  pkg/ddc/vineyard/transform_test.go
  pkg/ddc/vineyard/type.go
Labels: lgtm, needs-ok-to-test, approved

#3992 Docker build for pod metadata for vineyard
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#3832 from2023to2021
  pkg/controllers/v1alpha1/goosefs/suite_test.go
Labels: lgtm, needs-ok-to-test, approved

#3842 fixed typo in datamigrate_controller.go
  pkg/controllers/v1alpha1/datamigrate/datamigrate_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3848 fix Copyright time from 2022 to 2020 in file "pkg/controllers/v1alpha1/dataload/dataload_controller.go" line 2
  pkg/controllers/v1alpha1/dataload/dataload_controller.go
Labels: lgtm, needs-ok-to-test, approved

#3838 Corrected situation 3 at file 'constant.go' (there was Licence with c…
  api/v1alpha1/constant.go
Labels: lgtm, needs-ok-to-test, approved

#3834 modify the license
  api/v1alpha1/doc.go
Labels: lgtm, needs-ok-to-test, approved
