Repository fluid-cloudnative/fluid, pull requests merged in 2024-07, with the labels that each got.

#4178 dataset support pvc storageSize
  pkg/ddc/efc/create_volume.go
  pkg/utils/dataset.go
  pkg/utils/dataset/volume/create.go
  pkg/utils/dataset_test.go
Labels: lgtm, needs-ok-to-test, approved

#4187 Build docker images for specifying pvc storage size
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4188 docs: dev guide for en missing GOPATH setup
  docs/en/dev/how_to_develop.md
Labels: lgtm, needs-ok-to-test, approved

#4129 Update operation_helm.go
  pkg/ddc/base/operation_helm.go
Labels: lgtm, approved, ok-to-test

#4194 bugfix: allow users to override juicefs attr-cache and entry-cache options
  pkg/ddc/efc/create_volume.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/utils/annotations.go
  pkg/utils/map.go
Labels: lgtm, approved

#4197 Build docker images for fixing juicefs timeout
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4198 bugfix: fix early break when cleaning mount point in NodeUnpublishVolume
  pkg/csi/plugins/nodeserver.go
Labels: lgtm, approved

#4078 This pr is to add the translation of the Apache License notice
  cmd/thin/app/thin.go
Labels: needs-ok-to-test, approved

#4205 revert: "upgrade jindocache to 6.4.0 version (#4126)"
  charts/fluid/fluid/values.yaml
  charts/jindocache/CHANGELOG.md
  charts/jindocache/Chart.yaml
  charts/jindocache/values.yaml
  pkg/ddc/jindocache/const.go
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindocache/transform_fuse_test.go
  pkg/ddc/jindocache/transform_test.go
  pkg/utils/jindo/jindo.go
Labels: lgtm, approved

#4206 Build docker images for reverting jindoruntime from 6.4 to 6.2
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4207 Prepare 1.0.2
  Makefile
  charts/fluid/fluid/Chart.yaml
Labels: lgtm, approved

#4208 Delete the unused rbac roles for vineyard runtime.
  charts/fluid/fluid/templates/role/vineyard/rbac.yaml
Labels: lgtm, needs-ok-to-test, approved

#4210 Update docker image to fluid 1.0.2
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4212 bugfix: support sync ak/sk secret key-values in JindoRuntime
  charts/jindocache/CHANGELOG.md
  charts/jindocache/Chart.yaml
  charts/jindocache/templates/_helpers.tpl
  charts/jindocache/templates/fuse/daemonset.yaml
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindocache/templates/worker/statefulset.yaml
  charts/jindofsx/CHANGELOG.md
  charts/jindofsx/Chart.yaml
  charts/jindofsx/templates/_helpers.tpl
  charts/jindofsx/templates/fuse/daemonset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  charts/jindofsx/templates/worker/statefulset.yaml
Labels: lgtm, approved

#4215 del create pod role of juicefs runtime
  charts/fluid/fluid/templates/role/juicefs/rbac.yaml
  charts/juicefs/templates/role/rbac.yaml
Labels: lgtm, approved

#4216 refactor: separate image and tag in helm values
  charts/fluid/fluid/templates/_helpers.tpl
  charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
  charts/fluid/fluid/templates/controller/dataset_controller.yaml
  charts/fluid/fluid/templates/controller/efcruntime_controller.yaml
  charts/fluid/fluid/templates/controller/fluidapp_controller.yaml
  charts/fluid/fluid/templates/controller/goosefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/jindoruntime_controller.yaml
  charts/fluid/fluid/templates/controller/juicefsruntime_controller.yaml
  charts/fluid/fluid/templates/controller/thinruntime_controller.yaml
  charts/fluid/fluid/templates/controller/vineyardruntime_controller.yaml
  charts/fluid/fluid/templates/csi/daemonset.yaml
  charts/fluid/fluid/templates/upgrade/crd-upgrade.yaml
  charts/fluid/fluid/templates/webhook/webhook.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4218 Docker build for juicefs runtime refactor
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4217 Add no cache option to Makefile
  Makefile
Labels: lgtm, approved

#4220 update scorecard link
  README-zh_CN.md
  README.md
Labels: lgtm, approved

#4223 feat: pass extra args when building fuse sidecar mutators
  pkg/application/inject/fuse/injector.go
  pkg/application/inject/fuse/mutator/mutator.go
  pkg/application/inject/fuse/mutator/mutator_default.go
  pkg/application/inject/fuse/mutator/mutator_test.go
  pkg/application/inject/fuse/mutator/mutator_unprivileged.go
  pkg/common/types.go
Labels: lgtm, approved

#4224 enhance: add github actions workflow e2e tests
  .github/scripts/build-all-images.sh
  .github/scripts/deploy-fluid-to-kind.sh
  .github/scripts/gha-e2e.sh
  .github/workflows/kind-e2e.yml
  .github/workflows/project-check.yml
  test/e2etest/patch_node_label_test.go
  test/e2etest/suite_test.go
  test/e2etest/testdata/alluxioruntime-1.yaml
  test/e2etest/testdata/alluxioruntime-2.yaml
  test/e2etest/testdata/alluxioruntime-3.yaml
  test/e2etest/testdata/alluxioruntime-4.yaml
  test/e2etest/testdata/dataset-1.yaml
  test/e2etest/testdata/dataset-2.yaml
  test/e2etest/testdata/dataset-3.yaml
  test/e2etest/testdata/dataset-4.yaml
  test/gha-e2e/alluxio/dataset.yaml
  test/gha-e2e/alluxio/job.yaml
  test/gha-e2e/alluxio/test.sh
  test/gha-e2e/jindo/dataset.yaml
  test/gha-e2e/jindo/job.yaml
  test/gha-e2e/jindo/minio.yaml
  test/gha-e2e/jindo/test.sh
  test/gha-e2e/juicefs/dataset.yaml
  test/gha-e2e/juicefs/minio.yaml
  test/gha-e2e/juicefs/read_job.yaml
  test/gha-e2e/juicefs/redis.yaml
  test/gha-e2e/juicefs/test.sh
  test/gha-e2e/juicefs/write_job.yaml
  test/test.sh
  test/testcase1/testcase1_dataset.yaml
  test/testcase1/testcase1_runtime.yaml
  test/testcase2/runtime.yaml
  test/testcase2/testcase2_dataset.yaml
  test/testcase_basic/dataload.yaml
  test/testcase_basic/dataset.yaml
  test/testcase_basic/instructions.md
  test/testcase_basic/runtime.yaml
  test/testcase_basic/test.sh
  tools/diagnose-fluid-alluxio.sh
  tools/diagnose-fluid-jindo.sh
  tools/diagnose-fluid-juicefs.sh
Labels: lgtm, approved

#4234 fix Variable Naming Convention for DEFAULT_MASTER_RPC_PORT in CamelCase
  pkg/ddc/jindo/const.go
  pkg/ddc/jindo/transform.go
Labels: lgtm, approved

#4229 Change Constant Variable Naming Convention for CSI_DRIVER in camelCase format
  pkg/ddc/jindo/const.go
Labels: lgtm, approved

#4235 bugfix: fix version replace in gha-e2e
  .github/scripts/deploy-fluid-to-kind.sh
Labels: lgtm, approved

#4230 Update docker images for refactoring sidecar mutator
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
  pkg/ddc/jindo/const.go
  pkg/ddc/jindo/transform.go
Labels: lgtm, approved

#4236 juicefs: use exec in juicefs pod to avoid ignore signal
  pkg/ddc/juicefs/transform.go
  pkg/ddc/juicefs/transform_fuse.go
  pkg/ddc/juicefs/transform_fuse_test.go
  pkg/ddc/juicefs/transform_test.go
Labels: lgtm, approved

#4237 update juicefs default image
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4241 Feat:support dynamic mount of subpath format JuiceFS mount-points
  addons/dynamic-mount/juicefs/docker/mount.sh
Labels: lgtm, approved
