Repository fluid-cloudnative/fluid, pull requests merged in 2024-12, with the labels that each got.

#4421 Revert "fix: sort broken mountpoint and put subpaths at the end."
  pkg/csi/recover/recover.go
  pkg/utils/mountinfo/mountpoint.go
Labels: lgtm, approved

#4428 Support to set the resource configuration for Fluid webhook pod
  charts/fluid/fluid/templates/webhook/webhook.yaml
Labels: lgtm, approved

#4431 refactor: Optimize goosefs usage of istio
  charts/goosefs/templates/fuse/daemonset.yaml
  charts/goosefs/templates/master/statefulset.yaml
  charts/goosefs/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4434 Update committer list
  MAINTAINERS_COMMITTERS.md
Labels: lgtm, approved

#4436 refactor: Optimize alluxio usage of istio
  charts/alluxio/templates/fuse/daemonset.yaml
  charts/alluxio/templates/master/statefulset.yaml
  charts/alluxio/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4441 refactor: Optimize juicefs usage of istio
  charts/juicefs/templates/fuse/daemonset.yaml
  charts/juicefs/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4442 Build docker images for fixing istio label issue
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#4444 Fix LegacyKeyValueFormat issue
  addons/dynamic-mount/ossfs/docker/Dockerfile
  docker/Dockerfile.crds
  samples/vineyard/Dockerfile
Labels: lgtm, approved

#4447 refactor: Optimize thin usage of istio
  charts/thin/templates/fuse/daemonset.yaml
  charts/thin/templates/worker/statefuleset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4448 Update API docs
  docs/en/dev/api_doc.md
  docs/zh/dev/api_doc.md
Labels: lgtm, approved

#4453 bugfix: add pod anti affinity to master sts to make HA available
  charts/jindocache/templates/master/statefulset.yaml
  charts/jindofsx/templates/master/statefulset.yaml
  pkg/ddc/jindocache/transform.go
  pkg/ddc/jindofsx/transform.go
Labels: lgtm, approved

#4452 Update docker images with github.com/onsi/gomega
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm

#4457 refactor: Optimize etc usage of istio
  charts/efc/templates/fuse/daemonset.yaml
  charts/efc/templates/master/statefulset.yaml
  charts/efc/templates/worker/statefulset.yaml
Labels: lgtm, needs-ok-to-test, approved

#4459 Support configuration of k8s client QPS and burst in webhooks.
  cmd/webhook/app/webhook.go
Labels: approved

#4458 remove unused files
  pkg/application/inject/fuse/injector_test.go
  pkg/application/inject/fuse/mutator/mutator_default.go
  pkg/application/inject/fuse/mutator/mutator_unprivileged.go
  pkg/application/inject/fuse/poststart/check_fuse_unprivileged.go
  pkg/common/constants.go
Labels: lgtm, approved

#4461 Build docker images for webhook with QPS configuration
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved
