Repository fluid-cloudnative/fluid, pull requests merged in 2025-07, with the labels that each got.

#5160 Bump alpine to 3.20.6 and golang to 1.23.10
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.crds
  docker/Dockerfile.csi
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
  docker/Dockerfile.webhook
Labels: lgtm, approved

#5164 import self-maintainerd ddc-helm in dockerfile
  Makefile
  docker/Dockerfile.alluxioruntime
  docker/Dockerfile.application
  docker/Dockerfile.dataset
  docker/Dockerfile.efcruntime
  docker/Dockerfile.goosefsruntime
  docker/Dockerfile.jindoruntime
  docker/Dockerfile.juicefsruntime
  docker/Dockerfile.thinruntime
  docker/Dockerfile.vineyardruntime
Labels: lgtm, approved

#5162 Support building prefetch image
  Makefile
  docker/Dockerfile.fileprefetch
  tools/file-prefetcher/Dockerfile
Labels: lgtm, approved

#5165 enhance: optimize volume binding efficiency
  pkg/utils/dataset/volume/create.go
Labels: lgtm, approved

#5167 enhance: optimize helm status efficiency
  pkg/utils/helm/utils.go
Labels: lgtm, approved

#5166 Build candidate Docker image for version 1.0.6
  .circleci/config.yml
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#5171 disable sync schedule info in thinruntime
  pkg/ddc/thin/node.go
  pkg/ddc/thin/node_test.go
Labels: lgtm, approved

#5172 Build docker images for fixing reference dataset volume binding failure
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm

#5176 typofix: typo fix for FILE_PREFETCHER_IMAGE env variable
  charts/fluid/fluid/templates/webhook/webhook.yaml
Labels: lgtm, approved

#5123 Feature: support custom lifecycle configuration in thinruntimeprofile
  api/v1alpha1/openapi_generated.go
  api/v1alpha1/thinruntime_types.go
  charts/fluid/fluid/crds/data.fluid.io_thinruntimeprofiles.yaml
  charts/fluid/fluid/crds/data.fluid.io_thinruntimes.yaml
  charts/thin/templates/fuse/daemonset.yaml
  config/crd/bases/data.fluid.io_thinruntimeprofiles.yaml
  config/crd/bases/data.fluid.io_thinruntimes.yaml
  pkg/ddc/thin/transform_fuse.go
  pkg/ddc/thin/transform_fuse_test.go
  pkg/ddc/thin/type.go
Labels: lgtm, approved

#5185 Update runtime_dev_guide.md
  docs/zh/dev/runtime_dev_guide.md
Labels: lgtm, needs-ok-to-test, approved
