Repository fluid-cloudnative/fluid, pull requests merged in 2025-10, with the labels that each got.

#5252 feat(dashboard-ks-extension): migrate dataset-related pages and logic
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/BasicInfoStep.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataLoadStep.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/DataSourceStep.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/AddMountButton.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/EncryptOptionsInput.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/components/MountItem.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/styles.ts
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/types.ts
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/DataSourceStep/utils.ts
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/RuntimeStep.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/StepIndicator.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/components/YamlEditor.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/components/CreateDatasetModal/types.ts
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/Events/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/Metadata/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/ResourceStatus/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/detail/routes.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/datasets/list/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/shared/components/ResourceStatusStyles.tsx
Labels: lgtm, needs-ok-to-test, approved

#5254 feat(dashboard-ks-extension): migrate runtime-related pages and logic
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/Events/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/Metadata/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/ResourceStatus/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/detail/routes.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/list/index.tsx
  dashboard/fluid-ks-extension/extensions/fluid/src/pages/runtimes/runtimeMap.ts
Labels: lgtm, needs-ok-to-test, approved

#5266 fix(dashboard-ks-extension): resolve ejs template injection vulnerabi…
  dashboard/fluid-ks-extension/package.json
  dashboard/fluid-ks-extension/yarn.lock
Labels: lgtm, needs-ok-to-test, approved

#5268 Fix/dashboard ks extension dependency security vulnerabilities
  dashboard/fluid-ks-extension/package.json
  dashboard/fluid-ks-extension/yarn.lock
Labels: lgtm, approved

#5267 Build docker images for v1.0.8 alpha version
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#5272 fix(dashboard-ks-extension): update version to resolve path-to-regexp…
  dashboard/fluid-ks-extension/package.json
  dashboard/fluid-ks-extension/yarn.lock
Labels: lgtm
