Repository fluid-cloudnative/fluid, pull requests merged in 2025-08, with the labels that each got.

#5058 This PR is to add comments to TestPatchDatasetStatus in pkg\ddc\alluxio\cache_test.go.
  pkg/ddc/alluxio/cache_test.go
Labels: lgtm, needs-ok-to-test, approved

#5085 This PR is to add comments to TestJuiceFSEngine_queryCacheStatus in pkg/ddc/juicefs/cache_test.go.
  pkg/ddc/juicefs/cache_test.go
Labels: lgtm, approved, ok-to-test

#5198 Build docker images for supporting unique hostpath in sidecar mode
  charts/fluid/fluid/Chart.yaml
  charts/fluid/fluid/values.yaml
Labels: lgtm, approved

#5195 Fix broken link issue of CoC
  CONTRIBUTING.md
Labels: lgtm, approved

#5199 chore: bump helm version to v3.18.4
  Makefile
Labels: lgtm, approved

#5201 chore: update github actions e2e k8s version
  .github/workflows/kind-e2e.yml
Labels: lgtm, approved

#5210 refactor: remove "getting unavailable pods" code logic to avoid heavy pod listing
  pkg/ctrl/fuse.go
  pkg/ctrl/master.go
  pkg/ctrl/worker.go
  pkg/utils/kubeclient/daemonset.go
  pkg/utils/kubeclient/statefulset.go
  pkg/utils/kubeclient/statefulset_test.go
Labels: lgtm, approved

#5212 refactor: refactor alluxio unit tests with ginkgo
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/ddc/alluxio/alluxio_suite_test.go
  pkg/ddc/alluxio/api_gateway_test.go
  pkg/ddc/alluxio/cache_test.go
  pkg/ddc/alluxio/create_volume_test.go
  pkg/ddc/alluxio/dataset.go
  pkg/ddc/alluxio/dataset_test.go
  pkg/ddc/alluxio/delete_volume_test.go
  pkg/ddc/alluxio/engine.go
  pkg/ddc/alluxio/hcfs_test.go
  pkg/ddc/alluxio/load_data_test.go
  pkg/ddc/alluxio/master_internal_test.go
  pkg/ddc/alluxio/metadata_test.go
  pkg/ddc/alluxio/mock_utils.go
  pkg/ddc/alluxio/shutdown_test.go
  pkg/ddc/alluxio/status_test.go
  pkg/ddc/alluxio/ufs_test.go
Labels: lgtm, approved
